// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: auth/v1/auth.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserRole defines user permission levels.
type UserRole int32

const (
	// Default role (should not be used)
	UserRole_USER_ROLE_UNSPECIFIED UserRole = 0
	// Regular user
	UserRole_USER_ROLE_USER UserRole = 1
	// Administrator
	UserRole_USER_ROLE_ADMIN UserRole = 2
	// Super administrator
	UserRole_USER_ROLE_SUPER_ADMIN UserRole = 3
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "USER_ROLE_UNSPECIFIED",
		1: "USER_ROLE_USER",
		2: "USER_ROLE_ADMIN",
		3: "USER_ROLE_SUPER_ADMIN",
	}
	UserRole_value = map[string]int32{
		"USER_ROLE_UNSPECIFIED": 0,
		"USER_ROLE_USER":        1,
		"USER_ROLE_ADMIN":       2,
		"USER_ROLE_SUPER_ADMIN": 3,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_v1_auth_proto_enumTypes[0].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_auth_v1_auth_proto_enumTypes[0]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

// Platform defines device platform types.
type Platform int32

const (
	// Default platform (should not be used)
	Platform_PLATFORM_UNSPECIFIED Platform = 0
	// iOS mobile app
	Platform_PLATFORM_IOS Platform = 1
	// Android mobile app
	Platform_PLATFORM_ANDROID Platform = 2
	// Web browser
	Platform_PLATFORM_WEB Platform = 3
	// Desktop application
	Platform_PLATFORM_DESKTOP Platform = 4
	// TV application
	Platform_PLATFORM_TV Platform = 5
)

// Enum value maps for Platform.
var (
	Platform_name = map[int32]string{
		0: "PLATFORM_UNSPECIFIED",
		1: "PLATFORM_IOS",
		2: "PLATFORM_ANDROID",
		3: "PLATFORM_WEB",
		4: "PLATFORM_DESKTOP",
		5: "PLATFORM_TV",
	}
	Platform_value = map[string]int32{
		"PLATFORM_UNSPECIFIED": 0,
		"PLATFORM_IOS":         1,
		"PLATFORM_ANDROID":     2,
		"PLATFORM_WEB":         3,
		"PLATFORM_DESKTOP":     4,
		"PLATFORM_TV":          5,
	}
)

func (x Platform) Enum() *Platform {
	p := new(Platform)
	*p = x
	return p
}

func (x Platform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Platform) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_v1_auth_proto_enumTypes[1].Descriptor()
}

func (Platform) Type() protoreflect.EnumType {
	return &file_auth_v1_auth_proto_enumTypes[1]
}

func (x Platform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Platform.Descriptor instead.
func (Platform) EnumDescriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

// ErrorCode defines authentication error codes.
type ErrorCode int32

const (
	// No error
	ErrorCode_ERROR_CODE_UNSPECIFIED ErrorCode = 0
	// Token is expired
	ErrorCode_ERROR_CODE_TOKEN_EXPIRED ErrorCode = 1
	// Token signature is invalid
	ErrorCode_ERROR_CODE_INVALID_SIGNATURE ErrorCode = 2
	// Token version mismatch (global revocation)
	ErrorCode_ERROR_CODE_VERSION_MISMATCH ErrorCode = 3
	// User account is disabled
	ErrorCode_ERROR_CODE_USER_DISABLED ErrorCode = 4
	// IP address mismatch (strict mode)
	ErrorCode_ERROR_CODE_IP_MISMATCH ErrorCode = 5
	// Device fingerprint anomaly detected
	ErrorCode_ERROR_CODE_FINGERPRINT_ANOMALY ErrorCode = 6
	// Refresh token not found or expired
	ErrorCode_ERROR_CODE_REFRESH_TOKEN_INVALID ErrorCode = 7
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_TOKEN_EXPIRED",
		2: "ERROR_CODE_INVALID_SIGNATURE",
		3: "ERROR_CODE_VERSION_MISMATCH",
		4: "ERROR_CODE_USER_DISABLED",
		5: "ERROR_CODE_IP_MISMATCH",
		6: "ERROR_CODE_FINGERPRINT_ANOMALY",
		7: "ERROR_CODE_REFRESH_TOKEN_INVALID",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":           0,
		"ERROR_CODE_TOKEN_EXPIRED":         1,
		"ERROR_CODE_INVALID_SIGNATURE":     2,
		"ERROR_CODE_VERSION_MISMATCH":      3,
		"ERROR_CODE_USER_DISABLED":         4,
		"ERROR_CODE_IP_MISMATCH":           5,
		"ERROR_CODE_FINGERPRINT_ANOMALY":   6,
		"ERROR_CODE_REFRESH_TOKEN_INVALID": 7,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_v1_auth_proto_enumTypes[2].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_auth_v1_auth_proto_enumTypes[2]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

// VerifyTokenRequest contains the token to be verified.
type VerifyTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The JWT access token in the format: "eyJhbGc..."
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// Optional client IP address for strict mode validation.
	// If provided and strict mode is enabled, the token's bound IP must match.
	ClientIp string `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	// Optional device fingerprint for anomaly detection.
	// Significant changes in fingerprint may indicate account compromise.
	DeviceFingerprint string `protobuf:"bytes,3,opt,name=device_fingerprint,json=deviceFingerprint,proto3" json:"device_fingerprint,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VerifyTokenRequest) Reset() {
	*x = VerifyTokenRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenRequest) ProtoMessage() {}

func (x *VerifyTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *VerifyTokenRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *VerifyTokenRequest) GetDeviceFingerprint() string {
	if x != nil {
		return x.DeviceFingerprint
	}
	return ""
}

// VerifyTokenResponse contains the validated user information.
type VerifyTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the token is valid
	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	// User information (only present if valid=true)
	User *User `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	// Device information
	Device *Device `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
	// Failure reason (only present if valid=false)
	ErrorMessage string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Error code for client handling
	ErrorCode     ErrorCode `protobuf:"varint,5,opt,name=error_code,json=errorCode,proto3,enum=auth.v1.ErrorCode" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenResponse) Reset() {
	*x = VerifyTokenResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenResponse) ProtoMessage() {}

func (x *VerifyTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenResponse.ProtoReflect.Descriptor instead.
func (*VerifyTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyTokenResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *VerifyTokenResponse) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *VerifyTokenResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *VerifyTokenResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

// RefreshTokenRequest contains the refresh token.
type RefreshTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The refresh token
	RefreshToken string `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	// Device ID that owns this refresh token
	DeviceId      string `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// RefreshTokenResponse contains the new tokens.
type RefreshTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// New access token (30 min TTL)
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// New refresh token (30 day TTL)
	RefreshToken string `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	// Token expiration time
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// RevokeTokenRequest specifies which token to revoke.
type RevokeTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The access token to revoke
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// Reason for revocation (for audit logs)
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenRequest) Reset() {
	*x = RevokeTokenRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenRequest) ProtoMessage() {}

func (x *RevokeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *RevokeTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RevokeTokenRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// RevokeTokenResponse confirms the revocation.
type RevokeTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the revocation was successful
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenResponse) Reset() {
	*x = RevokeTokenResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenResponse) ProtoMessage() {}

func (x *RevokeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *RevokeTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// RevokeDeviceRequest specifies which device to remove.
type RevokeDeviceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID who owns the device
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Device ID to revoke
	DeviceId string `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Reason for revocation (for audit logs)
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeDeviceRequest) Reset() {
	*x = RevokeDeviceRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeDeviceRequest) ProtoMessage() {}

func (x *RevokeDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeDeviceRequest.ProtoReflect.Descriptor instead.
func (*RevokeDeviceRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *RevokeDeviceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RevokeDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RevokeDeviceRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// RevokeDeviceResponse confirms the device removal.
type RevokeDeviceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the revocation was successful
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Number of tokens invalidated
	TokensRevoked int32 `protobuf:"varint,2,opt,name=tokens_revoked,json=tokensRevoked,proto3" json:"tokens_revoked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeDeviceResponse) Reset() {
	*x = RevokeDeviceResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeDeviceResponse) ProtoMessage() {}

func (x *RevokeDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeDeviceResponse.ProtoReflect.Descriptor instead.
func (*RevokeDeviceResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *RevokeDeviceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RevokeDeviceResponse) GetTokensRevoked() int32 {
	if x != nil {
		return x.TokensRevoked
	}
	return 0
}

// GetUserDevicesRequest specifies which user's devices to fetch.
type GetUserDevicesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDevicesRequest) Reset() {
	*x = GetUserDevicesRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDevicesRequest) ProtoMessage() {}

func (x *GetUserDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDevicesRequest.ProtoReflect.Descriptor instead.
func (*GetUserDevicesRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserDevicesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetUserDevicesResponse contains the list of devices.
type GetUserDevicesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of active devices
	Devices       []*Device `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDevicesResponse) Reset() {
	*x = GetUserDevicesResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDevicesResponse) ProtoMessage() {}

func (x *GetUserDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDevicesResponse.ProtoReflect.Descriptor instead.
func (*GetUserDevicesResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserDevicesResponse) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

// ValidateTokenVersionRequest checks token version validity.
type ValidateTokenVersionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID from the token
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Token version from the token claims
	TokenVersion  int32 `protobuf:"varint,2,opt,name=token_version,json=tokenVersion,proto3" json:"token_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenVersionRequest) Reset() {
	*x = ValidateTokenVersionRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenVersionRequest) ProtoMessage() {}

func (x *ValidateTokenVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenVersionRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenVersionRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *ValidateTokenVersionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateTokenVersionRequest) GetTokenVersion() int32 {
	if x != nil {
		return x.TokenVersion
	}
	return 0
}

// ValidateTokenVersionResponse indicates version validity.
type ValidateTokenVersionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the token version is valid
	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	// Current token version for the user
	CurrentVersion int32 `protobuf:"varint,2,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ValidateTokenVersionResponse) Reset() {
	*x = ValidateTokenVersionResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenVersionResponse) ProtoMessage() {}

func (x *ValidateTokenVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenVersionResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenVersionResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{11}
}

func (x *ValidateTokenVersionResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenVersionResponse) GetCurrentVersion() int32 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

// User represents a user account.
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique user ID (UUID)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Phone number (masked for privacy: 138****5678)
	Phone string `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	// User role
	Role UserRole `protobuf:"varint,3,opt,name=role,proto3,enum=auth.v1.UserRole" json:"role,omitempty"`
	// Whether the account is disabled
	Disabled bool `protobuf:"varint,4,opt,name=disabled,proto3" json:"disabled,omitempty"`
	// Current token version (incremented on global revocation)
	TokenVersion int32 `protobuf:"varint,5,opt,name=token_version,json=tokenVersion,proto3" json:"token_version,omitempty"`
	// Account creation time
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_auth_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{12}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_USER_ROLE_UNSPECIFIED
}

func (x *User) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *User) GetTokenVersion() int32 {
	if x != nil {
		return x.TokenVersion
	}
	return 0
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Device represents a user's device session.
type Device struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique device ID (UUID)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// User ID who owns this device
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Client-generated device identifier
	DeviceId string `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Platform type
	Platform Platform `protobuf:"varint,4,opt,name=platform,proto3,enum=auth.v1.Platform" json:"platform,omitempty"`
	// Device fingerprint (for anomaly detection)
	Fingerprint string `protobuf:"bytes,5,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	// Bound IP address (for strict mode)
	IpAddress string `protobuf:"bytes,6,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// Last activity timestamp
	LastActive *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_active,json=lastActive,proto3" json:"last_active,omitempty"`
	// Device creation time
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_auth_v1_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{13}
}

func (x *Device) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Device) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Device) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Device) GetPlatform() Platform {
	if x != nil {
		return x.Platform
	}
	return Platform_PLATFORM_UNSPECIFIED
}

func (x *Device) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *Device) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Device) GetLastActive() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActive
	}
	return nil
}

func (x *Device) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_auth_v1_auth_proto protoreflect.FileDescriptor

const file_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x12auth/v1/auth.proto\x12\aauth.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x01\n" +
	"\x12VerifyTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1b\n" +
	"\tclient_ip\x18\x02 \x01(\tR\bclientIp\x12-\n" +
	"\x12device_fingerprint\x18\x03 \x01(\tR\x11deviceFingerprint\"\xcf\x01\n" +
	"\x13VerifyTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12!\n" +
	"\x04user\x18\x02 \x01(\v2\r.auth.v1.UserR\x04user\x12'\n" +
	"\x06device\x18\x03 \x01(\v2\x0f.auth.v1.DeviceR\x06device\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x121\n" +
	"\n" +
	"error_code\x18\x05 \x01(\x0e2\x12.auth.v1.ErrorCodeR\terrorCode\"W\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\"\x99\x01\n" +
	"\x14RefreshTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"O\n" +
	"\x12RevokeTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"/\n" +
	"\x13RevokeTokenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"c\n" +
	"\x13RevokeDeviceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"W\n" +
	"\x14RevokeDeviceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0etokens_revoked\x18\x02 \x01(\x05R\rtokensRevoked\"0\n" +
	"\x15GetUserDevicesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"C\n" +
	"\x16GetUserDevicesResponse\x12)\n" +
	"\adevices\x18\x01 \x03(\v2\x0f.auth.v1.DeviceR\adevices\"[\n" +
	"\x1bValidateTokenVersionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rtoken_version\x18\x02 \x01(\x05R\ftokenVersion\"]\n" +
	"\x1cValidateTokenVersionResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12'\n" +
	"\x0fcurrent_version\x18\x02 \x01(\x05R\x0ecurrentVersion\"\xcf\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12%\n" +
	"\x04role\x18\x03 \x01(\x0e2\x11.auth.v1.UserRoleR\x04role\x12\x1a\n" +
	"\bdisabled\x18\x04 \x01(\bR\bdisabled\x12#\n" +
	"\rtoken_version\x18\x05 \x01(\x05R\ftokenVersion\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xb6\x02\n" +
	"\x06Device\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12-\n" +
	"\bplatform\x18\x04 \x01(\x0e2\x11.auth.v1.PlatformR\bplatform\x12 \n" +
	"\vfingerprint\x18\x05 \x01(\tR\vfingerprint\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x06 \x01(\tR\tipAddress\x12;\n" +
	"\vlast_active\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastActive\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt*i\n" +
	"\bUserRole\x12\x19\n" +
	"\x15USER_ROLE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eUSER_ROLE_USER\x10\x01\x12\x13\n" +
	"\x0fUSER_ROLE_ADMIN\x10\x02\x12\x19\n" +
	"\x15USER_ROLE_SUPER_ADMIN\x10\x03*\x85\x01\n" +
	"\bPlatform\x12\x18\n" +
	"\x14PLATFORM_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPLATFORM_IOS\x10\x01\x12\x14\n" +
	"\x10PLATFORM_ANDROID\x10\x02\x12\x10\n" +
	"\fPLATFORM_WEB\x10\x03\x12\x14\n" +
	"\x10PLATFORM_DESKTOP\x10\x04\x12\x0f\n" +
	"\vPLATFORM_TV\x10\x05*\x8c\x02\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18ERROR_CODE_TOKEN_EXPIRED\x10\x01\x12 \n" +
	"\x1cERROR_CODE_INVALID_SIGNATURE\x10\x02\x12\x1f\n" +
	"\x1bERROR_CODE_VERSION_MISMATCH\x10\x03\x12\x1c\n" +
	"\x18ERROR_CODE_USER_DISABLED\x10\x04\x12\x1a\n" +
	"\x16ERROR_CODE_IP_MISMATCH\x10\x05\x12\"\n" +
	"\x1eERROR_CODE_FINGERPRINT_ANOMALY\x10\x06\x12$\n" +
	" ERROR_CODE_REFRESH_TOKEN_INVALID\x10\a2\xf3\x03\n" +
	"\vAuthService\x12H\n" +
	"\vVerifyToken\x12\x1b.auth.v1.VerifyTokenRequest\x1a\x1c.auth.v1.VerifyTokenResponse\x12K\n" +
	"\fRefreshToken\x12\x1c.auth.v1.RefreshTokenRequest\x1a\x1d.auth.v1.RefreshTokenResponse\x12H\n" +
	"\vRevokeToken\x12\x1b.auth.v1.RevokeTokenRequest\x1a\x1c.auth.v1.RevokeTokenResponse\x12K\n" +
	"\fRevokeDevice\x12\x1c.auth.v1.RevokeDeviceRequest\x1a\x1d.auth.v1.RevokeDeviceResponse\x12Q\n" +
	"\x0eGetUserDevices\x12\x1e.auth.v1.GetUserDevicesRequest\x1a\x1f.auth.v1.GetUserDevicesResponse\x12c\n" +
	"\x14ValidateTokenVersion\x12$.auth.v1.ValidateTokenVersionRequest\x1a%.auth.v1.ValidateTokenVersionResponseB=Z;github.com/xiaoxiao0301/listen-stream-v2/server/shared/proto/auth/v1;authv1b\x06proto3"

var (
	file_auth_v1_auth_proto_rawDescOnce sync.Once
	file_auth_v1_auth_proto_rawDescData []byte
)

func file_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)))
	})
	return file_auth_v1_auth_proto_rawDescData
}

var file_auth_v1_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_auth_v1_auth_proto_goTypes = []any{
	(UserRole)(0),                        // 0: auth.v1.UserRole
	(Platform)(0),                        // 1: auth.v1.Platform
	(ErrorCode)(0),                       // 2: auth.v1.ErrorCode
	(*VerifyTokenRequest)(nil),           // 3: auth.v1.VerifyTokenRequest
	(*VerifyTokenResponse)(nil),          // 4: auth.v1.VerifyTokenResponse
	(*RefreshTokenRequest)(nil),          // 5: auth.v1.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),         // 6: auth.v1.RefreshTokenResponse
	(*RevokeTokenRequest)(nil),           // 7: auth.v1.RevokeTokenRequest
	(*RevokeTokenResponse)(nil),          // 8: auth.v1.RevokeTokenResponse
	(*RevokeDeviceRequest)(nil),          // 9: auth.v1.RevokeDeviceRequest
	(*RevokeDeviceResponse)(nil),         // 10: auth.v1.RevokeDeviceResponse
	(*GetUserDevicesRequest)(nil),        // 11: auth.v1.GetUserDevicesRequest
	(*GetUserDevicesResponse)(nil),       // 12: auth.v1.GetUserDevicesResponse
	(*ValidateTokenVersionRequest)(nil),  // 13: auth.v1.ValidateTokenVersionRequest
	(*ValidateTokenVersionResponse)(nil), // 14: auth.v1.ValidateTokenVersionResponse
	(*User)(nil),                         // 15: auth.v1.User
	(*Device)(nil),                       // 16: auth.v1.Device
	(*timestamppb.Timestamp)(nil),        // 17: google.protobuf.Timestamp
}
var file_auth_v1_auth_proto_depIdxs = []int32{
	15, // 0: auth.v1.VerifyTokenResponse.user:type_name -> auth.v1.User
	16, // 1: auth.v1.VerifyTokenResponse.device:type_name -> auth.v1.Device
	2,  // 2: auth.v1.VerifyTokenResponse.error_code:type_name -> auth.v1.ErrorCode
	17, // 3: auth.v1.RefreshTokenResponse.expires_at:type_name -> google.protobuf.Timestamp
	16, // 4: auth.v1.GetUserDevicesResponse.devices:type_name -> auth.v1.Device
	0,  // 5: auth.v1.User.role:type_name -> auth.v1.UserRole
	17, // 6: auth.v1.User.created_at:type_name -> google.protobuf.Timestamp
	1,  // 7: auth.v1.Device.platform:type_name -> auth.v1.Platform
	17, // 8: auth.v1.Device.last_active:type_name -> google.protobuf.Timestamp
	17, // 9: auth.v1.Device.created_at:type_name -> google.protobuf.Timestamp
	3,  // 10: auth.v1.AuthService.VerifyToken:input_type -> auth.v1.VerifyTokenRequest
	5,  // 11: auth.v1.AuthService.RefreshToken:input_type -> auth.v1.RefreshTokenRequest
	7,  // 12: auth.v1.AuthService.RevokeToken:input_type -> auth.v1.RevokeTokenRequest
	9,  // 13: auth.v1.AuthService.RevokeDevice:input_type -> auth.v1.RevokeDeviceRequest
	11, // 14: auth.v1.AuthService.GetUserDevices:input_type -> auth.v1.GetUserDevicesRequest
	13, // 15: auth.v1.AuthService.ValidateTokenVersion:input_type -> auth.v1.ValidateTokenVersionRequest
	4,  // 16: auth.v1.AuthService.VerifyToken:output_type -> auth.v1.VerifyTokenResponse
	6,  // 17: auth.v1.AuthService.RefreshToken:output_type -> auth.v1.RefreshTokenResponse
	8,  // 18: auth.v1.AuthService.RevokeToken:output_type -> auth.v1.RevokeTokenResponse
	10, // 19: auth.v1.AuthService.RevokeDevice:output_type -> auth.v1.RevokeDeviceResponse
	12, // 20: auth.v1.AuthService.GetUserDevices:output_type -> auth.v1.GetUserDevicesResponse
	14, // 21: auth.v1.AuthService.ValidateTokenVersion:output_type -> auth.v1.ValidateTokenVersionResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_auth_v1_auth_proto_init() }
func file_auth_v1_auth_proto_init() {
	if File_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_auth_v1_auth_proto_depIdxs,
		EnumInfos:         file_auth_v1_auth_proto_enumTypes,
		MessageInfos:      file_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_auth_v1_auth_proto = out.File
	file_auth_v1_auth_proto_goTypes = nil
	file_auth_v1_auth_proto_depIdxs = nil
}
