# Elasticsearch Configuration for Listen Stream
# Single-node setup for development; scale to 3+ nodes for production

cluster.name: listen-stream
node.name: elasticsearch-1

# Paths
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs

# Network
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

# Cluster
discovery.type: single-node       # Change to "zen" for multi-node
cluster.initial_master_nodes: ["elasticsearch-1"]

# Security — disabled for development
xpack.security.enabled: false
xpack.security.enrollment.enabled: false
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false

# Memory
bootstrap.memory_lock: false       # Set true in production with ulimit
indices.memory.index_buffer_size: "20%"

# Thread pools
thread_pool.write.queue_size: 1000
thread_pool.search.queue_size: 1000

# Index lifecycle management (ILM) — default policy
xpack.ilm.enabled: true

# Monitoring — send to itself
xpack.monitoring.elasticsearch.collection.enabled: true
xpack.monitoring.collection.enabled: true
