// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: admin/v1/admin.proto

package adminv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExportFormat defines export file formats.
type ExportFormat int32

const (
	// Default format (should not be used)
	ExportFormat_EXPORT_FORMAT_UNSPECIFIED ExportFormat = 0
	// CSV format
	ExportFormat_EXPORT_FORMAT_CSV ExportFormat = 1
	// Excel format
	ExportFormat_EXPORT_FORMAT_EXCEL ExportFormat = 2
)

// Enum value maps for ExportFormat.
var (
	ExportFormat_name = map[int32]string{
		0: "EXPORT_FORMAT_UNSPECIFIED",
		1: "EXPORT_FORMAT_CSV",
		2: "EXPORT_FORMAT_EXCEL",
	}
	ExportFormat_value = map[string]int32{
		"EXPORT_FORMAT_UNSPECIFIED": 0,
		"EXPORT_FORMAT_CSV":         1,
		"EXPORT_FORMAT_EXCEL":       2,
	}
)

func (x ExportFormat) Enum() *ExportFormat {
	p := new(ExportFormat)
	*p = x
	return p
}

func (x ExportFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExportFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_admin_v1_admin_proto_enumTypes[0].Descriptor()
}

func (ExportFormat) Type() protoreflect.EnumType {
	return &file_admin_v1_admin_proto_enumTypes[0]
}

func (x ExportFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExportFormat.Descriptor instead.
func (ExportFormat) EnumDescriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

// GetSystemStatsRequest can optionally specify a time range.
type GetSystemStatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: start time for historical stats
	StartTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Optional: end time for historical stats
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemStatsRequest) Reset() {
	*x = GetSystemStatsRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemStatsRequest) ProtoMessage() {}

func (x *GetSystemStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemStatsRequest.ProtoReflect.Descriptor instead.
func (*GetSystemStatsRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *GetSystemStatsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetSystemStatsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

// GetSystemStatsResponse contains system statistics.
type GetSystemStatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current real-time metrics
	Realtime *RealTimeMetrics `protobuf:"bytes,1,opt,name=realtime,proto3" json:"realtime,omitempty"`
	// Historical daily statistics (if time range provided)
	DailyStats    []*DailyStat `protobuf:"bytes,2,rep,name=daily_stats,json=dailyStats,proto3" json:"daily_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemStatsResponse) Reset() {
	*x = GetSystemStatsResponse{}
	mi := &file_admin_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemStatsResponse) ProtoMessage() {}

func (x *GetSystemStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemStatsResponse.ProtoReflect.Descriptor instead.
func (*GetSystemStatsResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *GetSystemStatsResponse) GetRealtime() *RealTimeMetrics {
	if x != nil {
		return x.Realtime
	}
	return nil
}

func (x *GetSystemStatsResponse) GetDailyStats() []*DailyStat {
	if x != nil {
		return x.DailyStats
	}
	return nil
}

// GetUserInfoRequest specifies which user to query.
type GetUserInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID or phone number
	Identifier    string `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserInfoRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

// GetUserInfoResponse contains detailed user information.
type GetUserInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User basic info
	User *UserInfo `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// Active devices
	Devices []*DeviceInfo `protobuf:"bytes,2,rep,name=devices,proto3" json:"devices,omitempty"`
	// Usage statistics
	Stats         *UsageStats `protobuf:"bytes,3,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_admin_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserInfoResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetUserInfoResponse) GetDevices() []*DeviceInfo {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *GetUserInfoResponse) GetStats() *UsageStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// DisableUserRequest specifies which user to disable.
type DisableUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Reason for disabling (for audit)
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// Admin ID performing the action
	AdminId       string `protobuf:"bytes,3,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableUserRequest) Reset() {
	*x = DisableUserRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableUserRequest) ProtoMessage() {}

func (x *DisableUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableUserRequest.ProtoReflect.Descriptor instead.
func (*DisableUserRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *DisableUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DisableUserRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DisableUserRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

// DisableUserResponse confirms the action.
type DisableUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the operation was successful
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Number of tokens revoked
	TokensRevoked int32 `protobuf:"varint,2,opt,name=tokens_revoked,json=tokensRevoked,proto3" json:"tokens_revoked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableUserResponse) Reset() {
	*x = DisableUserResponse{}
	mi := &file_admin_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableUserResponse) ProtoMessage() {}

func (x *DisableUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableUserResponse.ProtoReflect.Descriptor instead.
func (*DisableUserResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *DisableUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DisableUserResponse) GetTokensRevoked() int32 {
	if x != nil {
		return x.TokensRevoked
	}
	return 0
}

// EnableUserRequest specifies which user to re-enable.
type EnableUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Admin ID performing the action
	AdminId       string `protobuf:"bytes,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableUserRequest) Reset() {
	*x = EnableUserRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableUserRequest) ProtoMessage() {}

func (x *EnableUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableUserRequest.ProtoReflect.Descriptor instead.
func (*EnableUserRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *EnableUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EnableUserRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

// EnableUserResponse confirms the action.
type EnableUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the operation was successful
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableUserResponse) Reset() {
	*x = EnableUserResponse{}
	mi := &file_admin_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableUserResponse) ProtoMessage() {}

func (x *EnableUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableUserResponse.ProtoReflect.Descriptor instead.
func (*EnableUserResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *EnableUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ListOperationLogsRequest specifies pagination and filtering.
type ListOperationLogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: filter by admin ID
	AdminId string `protobuf:"bytes,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	// Optional: filter by action type
	Action string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	// Optional: time range start
	StartTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Optional: time range end
	EndTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Pagination: page number (1-based)
	Page int32 `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	// Pagination: items per page (default: 20, max: 100)
	PageSize      int32 `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationLogsRequest) Reset() {
	*x = ListOperationLogsRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationLogsRequest) ProtoMessage() {}

func (x *ListOperationLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationLogsRequest.ProtoReflect.Descriptor instead.
func (*ListOperationLogsRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *ListOperationLogsRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

func (x *ListOperationLogsRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ListOperationLogsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ListOperationLogsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ListOperationLogsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOperationLogsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ListOperationLogsResponse contains paginated logs.
type ListOperationLogsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of operation logs
	Logs []*OperationLog `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	// Total count
	Total int32 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	// Current page
	Page int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	// Page size
	PageSize      int32 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationLogsResponse) Reset() {
	*x = ListOperationLogsResponse{}
	mi := &file_admin_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationLogsResponse) ProtoMessage() {}

func (x *ListOperationLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationLogsResponse.ProtoReflect.Descriptor instead.
func (*ListOperationLogsResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *ListOperationLogsResponse) GetLogs() []*OperationLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *ListOperationLogsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListOperationLogsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOperationLogsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ExportOperationLogsRequest specifies export parameters.
type ExportOperationLogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Export format
	Format ExportFormat `protobuf:"varint,1,opt,name=format,proto3,enum=admin.v1.ExportFormat" json:"format,omitempty"`
	// Optional: filter by admin ID
	AdminId string `protobuf:"bytes,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	// Optional: time range start
	StartTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Optional: time range end
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportOperationLogsRequest) Reset() {
	*x = ExportOperationLogsRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportOperationLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportOperationLogsRequest) ProtoMessage() {}

func (x *ExportOperationLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportOperationLogsRequest.ProtoReflect.Descriptor instead.
func (*ExportOperationLogsRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *ExportOperationLogsRequest) GetFormat() ExportFormat {
	if x != nil {
		return x.Format
	}
	return ExportFormat_EXPORT_FORMAT_UNSPECIFIED
}

func (x *ExportOperationLogsRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

func (x *ExportOperationLogsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ExportOperationLogsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

// ExportOperationLogsResponse contains the exported file.
type ExportOperationLogsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Download URL (signed, expires in 1 hour)
	DownloadUrl string `protobuf:"bytes,1,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	// File size in bytes
	FileSize int64 `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	// Number of records exported
	RecordCount   int32 `protobuf:"varint,3,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportOperationLogsResponse) Reset() {
	*x = ExportOperationLogsResponse{}
	mi := &file_admin_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportOperationLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportOperationLogsResponse) ProtoMessage() {}

func (x *ExportOperationLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportOperationLogsResponse.ProtoReflect.Descriptor instead.
func (*ExportOperationLogsResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{11}
}

func (x *ExportOperationLogsResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *ExportOperationLogsResponse) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *ExportOperationLogsResponse) GetRecordCount() int32 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

// RealTimeMetrics contains current system metrics.
type RealTimeMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total registered users
	TotalUsers int32 `protobuf:"varint,1,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	// Active users (today)
	ActiveUsersToday int32 `protobuf:"varint,2,opt,name=active_users_today,json=activeUsersToday,proto3" json:"active_users_today,omitempty"`
	// Total favorites
	TotalFavorites int32 `protobuf:"varint,3,opt,name=total_favorites,json=totalFavorites,proto3" json:"total_favorites,omitempty"`
	// Total playlists
	TotalPlaylists int32 `protobuf:"varint,4,opt,name=total_playlists,json=totalPlaylists,proto3" json:"total_playlists,omitempty"`
	// Total play history records
	TotalHistory int32 `protobuf:"varint,5,opt,name=total_history,json=totalHistory,proto3" json:"total_history,omitempty"`
	// Active WebSocket connections
	ActiveConnections int32 `protobuf:"varint,6,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	// Current QPS
	CurrentQps int32 `protobuf:"varint,7,opt,name=current_qps,json=currentQps,proto3" json:"current_qps,omitempty"`
	// Error rate (last 5 minutes)
	ErrorRate float32 `protobuf:"fixed32,8,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	// P99 latency (last 5 minutes, in ms)
	P99Latency    float32 `protobuf:"fixed32,9,opt,name=p99_latency,json=p99Latency,proto3" json:"p99_latency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealTimeMetrics) Reset() {
	*x = RealTimeMetrics{}
	mi := &file_admin_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealTimeMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealTimeMetrics) ProtoMessage() {}

func (x *RealTimeMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealTimeMetrics.ProtoReflect.Descriptor instead.
func (*RealTimeMetrics) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{12}
}

func (x *RealTimeMetrics) GetTotalUsers() int32 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *RealTimeMetrics) GetActiveUsersToday() int32 {
	if x != nil {
		return x.ActiveUsersToday
	}
	return 0
}

func (x *RealTimeMetrics) GetTotalFavorites() int32 {
	if x != nil {
		return x.TotalFavorites
	}
	return 0
}

func (x *RealTimeMetrics) GetTotalPlaylists() int32 {
	if x != nil {
		return x.TotalPlaylists
	}
	return 0
}

func (x *RealTimeMetrics) GetTotalHistory() int32 {
	if x != nil {
		return x.TotalHistory
	}
	return 0
}

func (x *RealTimeMetrics) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *RealTimeMetrics) GetCurrentQps() int32 {
	if x != nil {
		return x.CurrentQps
	}
	return 0
}

func (x *RealTimeMetrics) GetErrorRate() float32 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

func (x *RealTimeMetrics) GetP99Latency() float32 {
	if x != nil {
		return x.P99Latency
	}
	return 0
}

// DailyStat contains daily aggregated statistics.
type DailyStat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Date (YYYY-MM-DD)
	Date string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	// Total users (cumulative)
	TotalUsers int32 `protobuf:"varint,2,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	// Active users (daily)
	ActiveUsers int32 `protobuf:"varint,3,opt,name=active_users,json=activeUsers,proto3" json:"active_users,omitempty"`
	// New registrations
	NewUsers int32 `protobuf:"varint,4,opt,name=new_users,json=newUsers,proto3" json:"new_users,omitempty"`
	// Total favorites
	TotalFavorites int32 `protobuf:"varint,5,opt,name=total_favorites,json=totalFavorites,proto3" json:"total_favorites,omitempty"`
	// Total playlists
	TotalPlaylists int32 `protobuf:"varint,6,opt,name=total_playlists,json=totalPlaylists,proto3" json:"total_playlists,omitempty"`
	// Total history records
	TotalHistory int32 `protobuf:"varint,7,opt,name=total_history,json=totalHistory,proto3" json:"total_history,omitempty"`
	// SMS sent count
	SmsSent int32 `protobuf:"varint,8,opt,name=sms_sent,json=smsSent,proto3" json:"sms_sent,omitempty"`
	// SMS failed count
	SmsFailed int32 `protobuf:"varint,9,opt,name=sms_failed,json=smsFailed,proto3" json:"sms_failed,omitempty"`
	// API call count
	ApiCalls int32 `protobuf:"varint,10,opt,name=api_calls,json=apiCalls,proto3" json:"api_calls,omitempty"`
	// Error rate
	ErrorRate     float32 `protobuf:"fixed32,11,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyStat) Reset() {
	*x = DailyStat{}
	mi := &file_admin_v1_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyStat) ProtoMessage() {}

func (x *DailyStat) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyStat.ProtoReflect.Descriptor instead.
func (*DailyStat) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{13}
}

func (x *DailyStat) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyStat) GetTotalUsers() int32 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *DailyStat) GetActiveUsers() int32 {
	if x != nil {
		return x.ActiveUsers
	}
	return 0
}

func (x *DailyStat) GetNewUsers() int32 {
	if x != nil {
		return x.NewUsers
	}
	return 0
}

func (x *DailyStat) GetTotalFavorites() int32 {
	if x != nil {
		return x.TotalFavorites
	}
	return 0
}

func (x *DailyStat) GetTotalPlaylists() int32 {
	if x != nil {
		return x.TotalPlaylists
	}
	return 0
}

func (x *DailyStat) GetTotalHistory() int32 {
	if x != nil {
		return x.TotalHistory
	}
	return 0
}

func (x *DailyStat) GetSmsSent() int32 {
	if x != nil {
		return x.SmsSent
	}
	return 0
}

func (x *DailyStat) GetSmsFailed() int32 {
	if x != nil {
		return x.SmsFailed
	}
	return 0
}

func (x *DailyStat) GetApiCalls() int32 {
	if x != nil {
		return x.ApiCalls
	}
	return 0
}

func (x *DailyStat) GetErrorRate() float32 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

// UserInfo contains detailed user information.
type UserInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Phone number
	Phone string `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	// User role
	Role string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	// Whether disabled
	Disabled bool `protobuf:"varint,4,opt,name=disabled,proto3" json:"disabled,omitempty"`
	// Token version
	TokenVersion int32 `protobuf:"varint,5,opt,name=token_version,json=tokenVersion,proto3" json:"token_version,omitempty"`
	// Account creation time
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last login time
	LastLoginAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_login_at,json=lastLoginAt,proto3" json:"last_login_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_admin_v1_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{14}
}

func (x *UserInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserInfo) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *UserInfo) GetTokenVersion() int32 {
	if x != nil {
		return x.TokenVersion
	}
	return 0
}

func (x *UserInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserInfo) GetLastLoginAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLoginAt
	}
	return nil
}

// DeviceInfo contains device information.
type DeviceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Platform
	Platform string `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	// IP address
	IpAddress string `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// Last active time
	LastActive *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_active,json=lastActive,proto3" json:"last_active,omitempty"`
	// Device creation time
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_admin_v1_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{15}
}

func (x *DeviceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeviceInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *DeviceInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *DeviceInfo) GetLastActive() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActive
	}
	return nil
}

func (x *DeviceInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// UsageStats contains user usage statistics.
type UsageStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total favorites count
	FavoriteCount int32 `protobuf:"varint,1,opt,name=favorite_count,json=favoriteCount,proto3" json:"favorite_count,omitempty"`
	// Total playlists count
	PlaylistCount int32 `protobuf:"varint,2,opt,name=playlist_count,json=playlistCount,proto3" json:"playlist_count,omitempty"`
	// Play history count
	HistoryCount int32 `protobuf:"varint,3,opt,name=history_count,json=historyCount,proto3" json:"history_count,omitempty"`
	// Total play time (seconds)
	TotalPlayTime int64 `protobuf:"varint,4,opt,name=total_play_time,json=totalPlayTime,proto3" json:"total_play_time,omitempty"`
	// Login count
	LoginCount    int32 `protobuf:"varint,5,opt,name=login_count,json=loginCount,proto3" json:"login_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageStats) Reset() {
	*x = UsageStats{}
	mi := &file_admin_v1_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageStats) ProtoMessage() {}

func (x *UsageStats) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageStats.ProtoReflect.Descriptor instead.
func (*UsageStats) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{16}
}

func (x *UsageStats) GetFavoriteCount() int32 {
	if x != nil {
		return x.FavoriteCount
	}
	return 0
}

func (x *UsageStats) GetPlaylistCount() int32 {
	if x != nil {
		return x.PlaylistCount
	}
	return 0
}

func (x *UsageStats) GetHistoryCount() int32 {
	if x != nil {
		return x.HistoryCount
	}
	return 0
}

func (x *UsageStats) GetTotalPlayTime() int64 {
	if x != nil {
		return x.TotalPlayTime
	}
	return 0
}

func (x *UsageStats) GetLoginCount() int32 {
	if x != nil {
		return x.LoginCount
	}
	return 0
}

// OperationLog represents an admin operation.
type OperationLog struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Log ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Admin ID
	AdminId string `protobuf:"bytes,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	// Admin username
	AdminUsername string `protobuf:"bytes,3,opt,name=admin_username,json=adminUsername,proto3" json:"admin_username,omitempty"`
	// Action type
	Action string `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	// Target type (user, config, device, etc.)
	TargetType string `protobuf:"bytes,5,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	// Target ID
	TargetId string `protobuf:"bytes,6,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	// Before data (JSON)
	BeforeData *structpb.Struct `protobuf:"bytes,7,opt,name=before_data,json=beforeData,proto3" json:"before_data,omitempty"`
	// After data (JSON)
	AfterData *structpb.Struct `protobuf:"bytes,8,opt,name=after_data,json=afterData,proto3" json:"after_data,omitempty"`
	// Request ID (for tracing)
	RequestId string `protobuf:"bytes,9,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// IP address
	IpAddress string `protobuf:"bytes,10,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// User agent
	UserAgent string `protobuf:"bytes,11,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	// Status (success, failed)
	Status string `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	// Error message (if failed)
	ErrorMessage string `protobuf:"bytes,13,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Timestamp
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationLog) Reset() {
	*x = OperationLog{}
	mi := &file_admin_v1_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationLog) ProtoMessage() {}

func (x *OperationLog) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationLog.ProtoReflect.Descriptor instead.
func (*OperationLog) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{17}
}

func (x *OperationLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OperationLog) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

func (x *OperationLog) GetAdminUsername() string {
	if x != nil {
		return x.AdminUsername
	}
	return ""
}

func (x *OperationLog) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *OperationLog) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *OperationLog) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *OperationLog) GetBeforeData() *structpb.Struct {
	if x != nil {
		return x.BeforeData
	}
	return nil
}

func (x *OperationLog) GetAfterData() *structpb.Struct {
	if x != nil {
		return x.AfterData
	}
	return nil
}

func (x *OperationLog) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *OperationLog) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *OperationLog) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *OperationLog) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OperationLog) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *OperationLog) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_admin_v1_admin_proto protoreflect.FileDescriptor

const file_admin_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x14admin/v1/admin.proto\x12\badmin.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x89\x01\n" +
	"\x15GetSystemStatsRequest\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\x85\x01\n" +
	"\x16GetSystemStatsResponse\x125\n" +
	"\brealtime\x18\x01 \x01(\v2\x19.admin.v1.RealTimeMetricsR\brealtime\x124\n" +
	"\vdaily_stats\x18\x02 \x03(\v2\x13.admin.v1.DailyStatR\n" +
	"dailyStats\"4\n" +
	"\x12GetUserInfoRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\"\x99\x01\n" +
	"\x13GetUserInfoResponse\x12&\n" +
	"\x04user\x18\x01 \x01(\v2\x12.admin.v1.UserInfoR\x04user\x12.\n" +
	"\adevices\x18\x02 \x03(\v2\x14.admin.v1.DeviceInfoR\adevices\x12*\n" +
	"\x05stats\x18\x03 \x01(\v2\x14.admin.v1.UsageStatsR\x05stats\"`\n" +
	"\x12DisableUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x19\n" +
	"\badmin_id\x18\x03 \x01(\tR\aadminId\"V\n" +
	"\x13DisableUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0etokens_revoked\x18\x02 \x01(\x05R\rtokensRevoked\"G\n" +
	"\x11EnableUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\badmin_id\x18\x02 \x01(\tR\aadminId\".\n" +
	"\x12EnableUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xf0\x01\n" +
	"\x18ListOperationLogsRequest\x12\x19\n" +
	"\badmin_id\x18\x01 \x01(\tR\aadminId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\"\x8e\x01\n" +
	"\x19ListOperationLogsResponse\x12*\n" +
	"\x04logs\x18\x01 \x03(\v2\x16.admin.v1.OperationLogR\x04logs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xd9\x01\n" +
	"\x1aExportOperationLogsRequest\x12.\n" +
	"\x06format\x18\x01 \x01(\x0e2\x16.admin.v1.ExportFormatR\x06format\x12\x19\n" +
	"\badmin_id\x18\x02 \x01(\tR\aadminId\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\x80\x01\n" +
	"\x1bExportOperationLogsResponse\x12!\n" +
	"\fdownload_url\x18\x01 \x01(\tR\vdownloadUrl\x12\x1b\n" +
	"\tfile_size\x18\x02 \x01(\x03R\bfileSize\x12!\n" +
	"\frecord_count\x18\x03 \x01(\x05R\vrecordCount\"\xe7\x02\n" +
	"\x0fRealTimeMetrics\x12\x1f\n" +
	"\vtotal_users\x18\x01 \x01(\x05R\n" +
	"totalUsers\x12,\n" +
	"\x12active_users_today\x18\x02 \x01(\x05R\x10activeUsersToday\x12'\n" +
	"\x0ftotal_favorites\x18\x03 \x01(\x05R\x0etotalFavorites\x12'\n" +
	"\x0ftotal_playlists\x18\x04 \x01(\x05R\x0etotalPlaylists\x12#\n" +
	"\rtotal_history\x18\x05 \x01(\x05R\ftotalHistory\x12-\n" +
	"\x12active_connections\x18\x06 \x01(\x05R\x11activeConnections\x12\x1f\n" +
	"\vcurrent_qps\x18\a \x01(\x05R\n" +
	"currentQps\x12\x1d\n" +
	"\n" +
	"error_rate\x18\b \x01(\x02R\terrorRate\x12\x1f\n" +
	"\vp99_latency\x18\t \x01(\x02R\n" +
	"p99Latency\"\xed\x02\n" +
	"\tDailyStat\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x1f\n" +
	"\vtotal_users\x18\x02 \x01(\x05R\n" +
	"totalUsers\x12!\n" +
	"\factive_users\x18\x03 \x01(\x05R\vactiveUsers\x12\x1b\n" +
	"\tnew_users\x18\x04 \x01(\x05R\bnewUsers\x12'\n" +
	"\x0ftotal_favorites\x18\x05 \x01(\x05R\x0etotalFavorites\x12'\n" +
	"\x0ftotal_playlists\x18\x06 \x01(\x05R\x0etotalPlaylists\x12#\n" +
	"\rtotal_history\x18\a \x01(\x05R\ftotalHistory\x12\x19\n" +
	"\bsms_sent\x18\b \x01(\x05R\asmsSent\x12\x1d\n" +
	"\n" +
	"sms_failed\x18\t \x01(\x05R\tsmsFailed\x12\x1b\n" +
	"\tapi_calls\x18\n" +
	" \x01(\x05R\bapiCalls\x12\x1d\n" +
	"\n" +
	"error_rate\x18\v \x01(\x02R\terrorRate\"\x80\x02\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x1a\n" +
	"\bdisabled\x18\x04 \x01(\bR\bdisabled\x12#\n" +
	"\rtoken_version\x18\x05 \x01(\x05R\ftokenVersion\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12>\n" +
	"\rlast_login_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vlastLoginAt\"\xcf\x01\n" +
	"\n" +
	"DeviceInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12;\n" +
	"\vlast_active\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastActive\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xc8\x01\n" +
	"\n" +
	"UsageStats\x12%\n" +
	"\x0efavorite_count\x18\x01 \x01(\x05R\rfavoriteCount\x12%\n" +
	"\x0eplaylist_count\x18\x02 \x01(\x05R\rplaylistCount\x12#\n" +
	"\rhistory_count\x18\x03 \x01(\x05R\fhistoryCount\x12&\n" +
	"\x0ftotal_play_time\x18\x04 \x01(\x03R\rtotalPlayTime\x12\x1f\n" +
	"\vlogin_count\x18\x05 \x01(\x05R\n" +
	"loginCount\"\xfd\x03\n" +
	"\fOperationLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\badmin_id\x18\x02 \x01(\tR\aadminId\x12%\n" +
	"\x0eadmin_username\x18\x03 \x01(\tR\radminUsername\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x1f\n" +
	"\vtarget_type\x18\x05 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x06 \x01(\tR\btargetId\x128\n" +
	"\vbefore_data\x18\a \x01(\v2\x17.google.protobuf.StructR\n" +
	"beforeData\x126\n" +
	"\n" +
	"after_data\x18\b \x01(\v2\x17.google.protobuf.StructR\tafterData\x12\x1d\n" +
	"\n" +
	"request_id\x18\t \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\n" +
	" \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\v \x01(\tR\tuserAgent\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\r \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt*]\n" +
	"\fExportFormat\x12\x1d\n" +
	"\x19EXPORT_FORMAT_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11EXPORT_FORMAT_CSV\x10\x01\x12\x17\n" +
	"\x13EXPORT_FORMAT_EXCEL\x10\x022\x86\x04\n" +
	"\fAdminService\x12S\n" +
	"\x0eGetSystemStats\x12\x1f.admin.v1.GetSystemStatsRequest\x1a .admin.v1.GetSystemStatsResponse\x12J\n" +
	"\vGetUserInfo\x12\x1c.admin.v1.GetUserInfoRequest\x1a\x1d.admin.v1.GetUserInfoResponse\x12J\n" +
	"\vDisableUser\x12\x1c.admin.v1.DisableUserRequest\x1a\x1d.admin.v1.DisableUserResponse\x12G\n" +
	"\n" +
	"EnableUser\x12\x1b.admin.v1.EnableUserRequest\x1a\x1c.admin.v1.EnableUserResponse\x12\\\n" +
	"\x11ListOperationLogs\x12\".admin.v1.ListOperationLogsRequest\x1a#.admin.v1.ListOperationLogsResponse\x12b\n" +
	"\x13ExportOperationLogs\x12$.admin.v1.ExportOperationLogsRequest\x1a%.admin.v1.ExportOperationLogsResponseB?Z=github.com/xiaoxiao0301/listen-stream-v2/server/shared/proto/admin/v1;adminv1b\x06proto3"

var (
	file_admin_v1_admin_proto_rawDescOnce sync.Once
	file_admin_v1_admin_proto_rawDescData []byte
)

func file_admin_v1_admin_proto_rawDescGZIP() []byte {
	file_admin_v1_admin_proto_rawDescOnce.Do(func() {
		file_admin_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_v1_admin_proto_rawDesc), len(file_admin_v1_admin_proto_rawDesc)))
	})
	return file_admin_v1_admin_proto_rawDescData
}

var file_admin_v1_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_admin_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_admin_v1_admin_proto_goTypes = []any{
	(ExportFormat)(0),                   // 0: admin.v1.ExportFormat
	(*GetSystemStatsRequest)(nil),       // 1: admin.v1.GetSystemStatsRequest
	(*GetSystemStatsResponse)(nil),      // 2: admin.v1.GetSystemStatsResponse
	(*GetUserInfoRequest)(nil),          // 3: admin.v1.GetUserInfoRequest
	(*GetUserInfoResponse)(nil),         // 4: admin.v1.GetUserInfoResponse
	(*DisableUserRequest)(nil),          // 5: admin.v1.DisableUserRequest
	(*DisableUserResponse)(nil),         // 6: admin.v1.DisableUserResponse
	(*EnableUserRequest)(nil),           // 7: admin.v1.EnableUserRequest
	(*EnableUserResponse)(nil),          // 8: admin.v1.EnableUserResponse
	(*ListOperationLogsRequest)(nil),    // 9: admin.v1.ListOperationLogsRequest
	(*ListOperationLogsResponse)(nil),   // 10: admin.v1.ListOperationLogsResponse
	(*ExportOperationLogsRequest)(nil),  // 11: admin.v1.ExportOperationLogsRequest
	(*ExportOperationLogsResponse)(nil), // 12: admin.v1.ExportOperationLogsResponse
	(*RealTimeMetrics)(nil),             // 13: admin.v1.RealTimeMetrics
	(*DailyStat)(nil),                   // 14: admin.v1.DailyStat
	(*UserInfo)(nil),                    // 15: admin.v1.UserInfo
	(*DeviceInfo)(nil),                  // 16: admin.v1.DeviceInfo
	(*UsageStats)(nil),                  // 17: admin.v1.UsageStats
	(*OperationLog)(nil),                // 18: admin.v1.OperationLog
	(*timestamppb.Timestamp)(nil),       // 19: google.protobuf.Timestamp
	(*structpb.Struct)(nil),             // 20: google.protobuf.Struct
}
var file_admin_v1_admin_proto_depIdxs = []int32{
	19, // 0: admin.v1.GetSystemStatsRequest.start_time:type_name -> google.protobuf.Timestamp
	19, // 1: admin.v1.GetSystemStatsRequest.end_time:type_name -> google.protobuf.Timestamp
	13, // 2: admin.v1.GetSystemStatsResponse.realtime:type_name -> admin.v1.RealTimeMetrics
	14, // 3: admin.v1.GetSystemStatsResponse.daily_stats:type_name -> admin.v1.DailyStat
	15, // 4: admin.v1.GetUserInfoResponse.user:type_name -> admin.v1.UserInfo
	16, // 5: admin.v1.GetUserInfoResponse.devices:type_name -> admin.v1.DeviceInfo
	17, // 6: admin.v1.GetUserInfoResponse.stats:type_name -> admin.v1.UsageStats
	19, // 7: admin.v1.ListOperationLogsRequest.start_time:type_name -> google.protobuf.Timestamp
	19, // 8: admin.v1.ListOperationLogsRequest.end_time:type_name -> google.protobuf.Timestamp
	18, // 9: admin.v1.ListOperationLogsResponse.logs:type_name -> admin.v1.OperationLog
	0,  // 10: admin.v1.ExportOperationLogsRequest.format:type_name -> admin.v1.ExportFormat
	19, // 11: admin.v1.ExportOperationLogsRequest.start_time:type_name -> google.protobuf.Timestamp
	19, // 12: admin.v1.ExportOperationLogsRequest.end_time:type_name -> google.protobuf.Timestamp
	19, // 13: admin.v1.UserInfo.created_at:type_name -> google.protobuf.Timestamp
	19, // 14: admin.v1.UserInfo.last_login_at:type_name -> google.protobuf.Timestamp
	19, // 15: admin.v1.DeviceInfo.last_active:type_name -> google.protobuf.Timestamp
	19, // 16: admin.v1.DeviceInfo.created_at:type_name -> google.protobuf.Timestamp
	20, // 17: admin.v1.OperationLog.before_data:type_name -> google.protobuf.Struct
	20, // 18: admin.v1.OperationLog.after_data:type_name -> google.protobuf.Struct
	19, // 19: admin.v1.OperationLog.created_at:type_name -> google.protobuf.Timestamp
	1,  // 20: admin.v1.AdminService.GetSystemStats:input_type -> admin.v1.GetSystemStatsRequest
	3,  // 21: admin.v1.AdminService.GetUserInfo:input_type -> admin.v1.GetUserInfoRequest
	5,  // 22: admin.v1.AdminService.DisableUser:input_type -> admin.v1.DisableUserRequest
	7,  // 23: admin.v1.AdminService.EnableUser:input_type -> admin.v1.EnableUserRequest
	9,  // 24: admin.v1.AdminService.ListOperationLogs:input_type -> admin.v1.ListOperationLogsRequest
	11, // 25: admin.v1.AdminService.ExportOperationLogs:input_type -> admin.v1.ExportOperationLogsRequest
	2,  // 26: admin.v1.AdminService.GetSystemStats:output_type -> admin.v1.GetSystemStatsResponse
	4,  // 27: admin.v1.AdminService.GetUserInfo:output_type -> admin.v1.GetUserInfoResponse
	6,  // 28: admin.v1.AdminService.DisableUser:output_type -> admin.v1.DisableUserResponse
	8,  // 29: admin.v1.AdminService.EnableUser:output_type -> admin.v1.EnableUserResponse
	10, // 30: admin.v1.AdminService.ListOperationLogs:output_type -> admin.v1.ListOperationLogsResponse
	12, // 31: admin.v1.AdminService.ExportOperationLogs:output_type -> admin.v1.ExportOperationLogsResponse
	26, // [26:32] is the sub-list for method output_type
	20, // [20:26] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_admin_v1_admin_proto_init() }
func file_admin_v1_admin_proto_init() {
	if File_admin_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_v1_admin_proto_rawDesc), len(file_admin_v1_admin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_v1_admin_proto_goTypes,
		DependencyIndexes: file_admin_v1_admin_proto_depIdxs,
		EnumInfos:         file_admin_v1_admin_proto_enumTypes,
		MessageInfos:      file_admin_v1_admin_proto_msgTypes,
	}.Build()
	File_admin_v1_admin_proto = out.File
	file_admin_v1_admin_proto_goTypes = nil
	file_admin_v1_admin_proto_depIdxs = nil
}
