// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: sync/v1/sync.proto

package syncv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SyncService_TriggerSync_FullMethodName            = "/sync.v1.SyncService/TriggerSync"
	SyncService_GetOfflineMessages_FullMethodName     = "/sync.v1.SyncService/GetOfflineMessages"
	SyncService_AckMessage_FullMethodName             = "/sync.v1.SyncService/AckMessage"
	SyncService_GetConnectionStats_FullMethodName     = "/sync.v1.SyncService/GetConnectionStats"
	SyncService_BroadcastSystemMessage_FullMethodName = "/sync.v1.SyncService/BroadcastSystemMessage"
)

// SyncServiceClient is the client API for SyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SyncService manages real-time synchronization of user data across devices.
//
// While WebSocket connections are handled via HTTP, this service provides
// RPCs for triggering sync events and managing offline messages.
type SyncServiceClient interface {
	// TriggerSync broadcasts a sync event to all connected devices for a user.
	//
	// Called by other services (user-svc, auth-svc) when data changes.
	TriggerSync(ctx context.Context, in *TriggerSyncRequest, opts ...grpc.CallOption) (*TriggerSyncResponse, error)
	// GetOfflineMessages retrieves messages queued while the user was offline.
	//
	// Called when a client reconnects to catch up on missed events.
	GetOfflineMessages(ctx context.Context, in *GetOfflineMessagesRequest, opts ...grpc.CallOption) (*GetOfflineMessagesResponse, error)
	// AckMessage acknowledges receipt of a message, removing it from the offline queue.
	AckMessage(ctx context.Context, in *AckMessageRequest, opts ...grpc.CallOption) (*AckMessageResponse, error)
	// GetConnectionStats returns connection statistics for monitoring.
	GetConnectionStats(ctx context.Context, in *GetConnectionStatsRequest, opts ...grpc.CallOption) (*GetConnectionStatsResponse, error)
	// BroadcastSystemMessage sends a system-wide message to all connected users.
	//
	// Used for maintenance notifications, etc.
	BroadcastSystemMessage(ctx context.Context, in *BroadcastSystemMessageRequest, opts ...grpc.CallOption) (*BroadcastSystemMessageResponse, error)
}

type syncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncServiceClient(cc grpc.ClientConnInterface) SyncServiceClient {
	return &syncServiceClient{cc}
}

func (c *syncServiceClient) TriggerSync(ctx context.Context, in *TriggerSyncRequest, opts ...grpc.CallOption) (*TriggerSyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerSyncResponse)
	err := c.cc.Invoke(ctx, SyncService_TriggerSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncServiceClient) GetOfflineMessages(ctx context.Context, in *GetOfflineMessagesRequest, opts ...grpc.CallOption) (*GetOfflineMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOfflineMessagesResponse)
	err := c.cc.Invoke(ctx, SyncService_GetOfflineMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncServiceClient) AckMessage(ctx context.Context, in *AckMessageRequest, opts ...grpc.CallOption) (*AckMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckMessageResponse)
	err := c.cc.Invoke(ctx, SyncService_AckMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncServiceClient) GetConnectionStats(ctx context.Context, in *GetConnectionStatsRequest, opts ...grpc.CallOption) (*GetConnectionStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConnectionStatsResponse)
	err := c.cc.Invoke(ctx, SyncService_GetConnectionStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncServiceClient) BroadcastSystemMessage(ctx context.Context, in *BroadcastSystemMessageRequest, opts ...grpc.CallOption) (*BroadcastSystemMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BroadcastSystemMessageResponse)
	err := c.cc.Invoke(ctx, SyncService_BroadcastSystemMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncServiceServer is the server API for SyncService service.
// All implementations must embed UnimplementedSyncServiceServer
// for forward compatibility.
//
// SyncService manages real-time synchronization of user data across devices.
//
// While WebSocket connections are handled via HTTP, this service provides
// RPCs for triggering sync events and managing offline messages.
type SyncServiceServer interface {
	// TriggerSync broadcasts a sync event to all connected devices for a user.
	//
	// Called by other services (user-svc, auth-svc) when data changes.
	TriggerSync(context.Context, *TriggerSyncRequest) (*TriggerSyncResponse, error)
	// GetOfflineMessages retrieves messages queued while the user was offline.
	//
	// Called when a client reconnects to catch up on missed events.
	GetOfflineMessages(context.Context, *GetOfflineMessagesRequest) (*GetOfflineMessagesResponse, error)
	// AckMessage acknowledges receipt of a message, removing it from the offline queue.
	AckMessage(context.Context, *AckMessageRequest) (*AckMessageResponse, error)
	// GetConnectionStats returns connection statistics for monitoring.
	GetConnectionStats(context.Context, *GetConnectionStatsRequest) (*GetConnectionStatsResponse, error)
	// BroadcastSystemMessage sends a system-wide message to all connected users.
	//
	// Used for maintenance notifications, etc.
	BroadcastSystemMessage(context.Context, *BroadcastSystemMessageRequest) (*BroadcastSystemMessageResponse, error)
	mustEmbedUnimplementedSyncServiceServer()
}

// UnimplementedSyncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSyncServiceServer struct{}

func (UnimplementedSyncServiceServer) TriggerSync(context.Context, *TriggerSyncRequest) (*TriggerSyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerSync not implemented")
}
func (UnimplementedSyncServiceServer) GetOfflineMessages(context.Context, *GetOfflineMessagesRequest) (*GetOfflineMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOfflineMessages not implemented")
}
func (UnimplementedSyncServiceServer) AckMessage(context.Context, *AckMessageRequest) (*AckMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AckMessage not implemented")
}
func (UnimplementedSyncServiceServer) GetConnectionStats(context.Context, *GetConnectionStatsRequest) (*GetConnectionStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConnectionStats not implemented")
}
func (UnimplementedSyncServiceServer) BroadcastSystemMessage(context.Context, *BroadcastSystemMessageRequest) (*BroadcastSystemMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BroadcastSystemMessage not implemented")
}
func (UnimplementedSyncServiceServer) mustEmbedUnimplementedSyncServiceServer() {}
func (UnimplementedSyncServiceServer) testEmbeddedByValue()                     {}

// UnsafeSyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncServiceServer will
// result in compilation errors.
type UnsafeSyncServiceServer interface {
	mustEmbedUnimplementedSyncServiceServer()
}

func RegisterSyncServiceServer(s grpc.ServiceRegistrar, srv SyncServiceServer) {
	// If the following call panics, it indicates UnimplementedSyncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SyncService_ServiceDesc, srv)
}

func _SyncService_TriggerSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).TriggerSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncService_TriggerSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).TriggerSync(ctx, req.(*TriggerSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncService_GetOfflineMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOfflineMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).GetOfflineMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncService_GetOfflineMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).GetOfflineMessages(ctx, req.(*GetOfflineMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncService_AckMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).AckMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncService_AckMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).AckMessage(ctx, req.(*AckMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncService_GetConnectionStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnectionStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).GetConnectionStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncService_GetConnectionStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).GetConnectionStats(ctx, req.(*GetConnectionStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncService_BroadcastSystemMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastSystemMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).BroadcastSystemMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncService_BroadcastSystemMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).BroadcastSystemMessage(ctx, req.(*BroadcastSystemMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SyncService_ServiceDesc is the grpc.ServiceDesc for SyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sync.v1.SyncService",
	HandlerType: (*SyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TriggerSync",
			Handler:    _SyncService_TriggerSync_Handler,
		},
		{
			MethodName: "GetOfflineMessages",
			Handler:    _SyncService_GetOfflineMessages_Handler,
		},
		{
			MethodName: "AckMessage",
			Handler:    _SyncService_AckMessage_Handler,
		},
		{
			MethodName: "GetConnectionStats",
			Handler:    _SyncService_GetConnectionStats_Handler,
		},
		{
			MethodName: "BroadcastSystemMessage",
			Handler:    _SyncService_BroadcastSystemMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sync/v1/sync.proto",
}
