// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: sync/v1/sync.proto

package syncv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TriggerSyncRequest specifies a sync event to broadcast.
type TriggerSyncRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID to notify
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Event type (e.g., "favorite.added", "playlist.updated")
	EventType string `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// Event payload (flexible JSON structure)
	Data *structpb.Struct `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// Optional: exclude a specific device from receiving this event
	// (useful when the originating device doesn't need to be notified)
	ExcludeDeviceId string `protobuf:"bytes,4,opt,name=exclude_device_id,json=excludeDeviceId,proto3" json:"exclude_device_id,omitempty"`
	// Whether to queue this message if the user is offline
	QueueIfOffline bool `protobuf:"varint,5,opt,name=queue_if_offline,json=queueIfOffline,proto3" json:"queue_if_offline,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TriggerSyncRequest) Reset() {
	*x = TriggerSyncRequest{}
	mi := &file_sync_v1_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSyncRequest) ProtoMessage() {}

func (x *TriggerSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSyncRequest.ProtoReflect.Descriptor instead.
func (*TriggerSyncRequest) Descriptor() ([]byte, []int) {
	return file_sync_v1_sync_proto_rawDescGZIP(), []int{0}
}

func (x *TriggerSyncRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TriggerSyncRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *TriggerSyncRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TriggerSyncRequest) GetExcludeDeviceId() string {
	if x != nil {
		return x.ExcludeDeviceId
	}
	return ""
}

func (x *TriggerSyncRequest) GetQueueIfOffline() bool {
	if x != nil {
		return x.QueueIfOffline
	}
	return false
}

// TriggerSyncResponse confirms the event was sent.
type TriggerSyncResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the event was successfully broadcast
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Number of devices that received the event
	DevicesNotified int32 `protobuf:"varint,2,opt,name=devices_notified,json=devicesNotified,proto3" json:"devices_notified,omitempty"`
	// Whether the message was queued for offline delivery
	Queued        bool `protobuf:"varint,3,opt,name=queued,proto3" json:"queued,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSyncResponse) Reset() {
	*x = TriggerSyncResponse{}
	mi := &file_sync_v1_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSyncResponse) ProtoMessage() {}

func (x *TriggerSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSyncResponse.ProtoReflect.Descriptor instead.
func (*TriggerSyncResponse) Descriptor() ([]byte, []int) {
	return file_sync_v1_sync_proto_rawDescGZIP(), []int{1}
}

func (x *TriggerSyncResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TriggerSyncResponse) GetDevicesNotified() int32 {
	if x != nil {
		return x.DevicesNotified
	}
	return 0
}

func (x *TriggerSyncResponse) GetQueued() bool {
	if x != nil {
		return x.Queued
	}
	return false
}

// GetOfflineMessagesRequest fetches queued messages.
type GetOfflineMessagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Optional: only fetch messages after this ID (for pagination)
	AfterMessageId string `protobuf:"bytes,2,opt,name=after_message_id,json=afterMessageId,proto3" json:"after_message_id,omitempty"`
	// Maximum number of messages to return (default: 100, max: 1000)
	Limit         int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOfflineMessagesRequest) Reset() {
	*x = GetOfflineMessagesRequest{}
	mi := &file_sync_v1_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOfflineMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOfflineMessagesRequest) ProtoMessage() {}

func (x *GetOfflineMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOfflineMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetOfflineMessagesRequest) Descriptor() ([]byte, []int) {
	return file_sync_v1_sync_proto_rawDescGZIP(), []int{2}
}

func (x *GetOfflineMessagesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetOfflineMessagesRequest) GetAfterMessageId() string {
	if x != nil {
		return x.AfterMessageId
	}
	return ""
}

func (x *GetOfflineMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// GetOfflineMessagesResponse contains queued messages.
type GetOfflineMessagesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of offline messages (oldest first)
	Messages []*SyncMessage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	// Whether there are more messages (for pagination)
	HasMore       bool `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOfflineMessagesResponse) Reset() {
	*x = GetOfflineMessagesResponse{}
	mi := &file_sync_v1_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOfflineMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOfflineMessagesResponse) ProtoMessage() {}

func (x *GetOfflineMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOfflineMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetOfflineMessagesResponse) Descriptor() ([]byte, []int) {
	return file_sync_v1_sync_proto_rawDescGZIP(), []int{3}
}

func (x *GetOfflineMessagesResponse) GetMessages() []*SyncMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetOfflineMessagesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// AckMessageRequest acknowledges message receipt.
type AckMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Message ID to acknowledge
	MessageId string `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// ACK token from the message (for verification)
	AckToken      string `protobuf:"bytes,3,opt,name=ack_token,json=ackToken,proto3" json:"ack_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckMessageRequest) Reset() {
	*x = AckMessageRequest{}
	mi := &file_sync_v1_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMessageRequest) ProtoMessage() {}

func (x *AckMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMessageRequest.ProtoReflect.Descriptor instead.
func (*AckMessageRequest) Descriptor() ([]byte, []int) {
	return file_sync_v1_sync_proto_rawDescGZIP(), []int{4}
}

func (x *AckMessageRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AckMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *AckMessageRequest) GetAckToken() string {
	if x != nil {
		return x.AckToken
	}
	return ""
}

// AckMessageResponse confirms the acknowledgment.
type AckMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the acknowledgment was successful
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckMessageResponse) Reset() {
	*x = AckMessageResponse{}
	mi := &file_sync_v1_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMessageResponse) ProtoMessage() {}

func (x *AckMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMessageResponse.ProtoReflect.Descriptor instead.
func (*AckMessageResponse) Descriptor() ([]byte, []int) {
	return file_sync_v1_sync_proto_rawDescGZIP(), []int{5}
}

func (x *AckMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetConnectionStatsRequest fetches connection statistics.
type GetConnectionStatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: filter by user ID
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectionStatsRequest) Reset() {
	*x = GetConnectionStatsRequest{}
	mi := &file_sync_v1_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionStatsRequest) ProtoMessage() {}

func (x *GetConnectionStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionStatsRequest.ProtoReflect.Descriptor instead.
func (*GetConnectionStatsRequest) Descriptor() ([]byte, []int) {
	return file_sync_v1_sync_proto_rawDescGZIP(), []int{6}
}

func (x *GetConnectionStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetConnectionStatsResponse contains connection statistics.
type GetConnectionStatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total active WebSocket connections
	TotalConnections int32 `protobuf:"varint,1,opt,name=total_connections,json=totalConnections,proto3" json:"total_connections,omitempty"`
	// Unique connected users
	UniqueUsers int32 `protobuf:"varint,2,opt,name=unique_users,json=uniqueUsers,proto3" json:"unique_users,omitempty"`
	// Breakdown by platform
	PlatformStats []*PlatformStats `protobuf:"bytes,3,rep,name=platform_stats,json=platformStats,proto3" json:"platform_stats,omitempty"`
	// If user_id was provided, return specific user's connections
	UserConnections []*UserConnection `protobuf:"bytes,4,rep,name=user_connections,json=userConnections,proto3" json:"user_connections,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetConnectionStatsResponse) Reset() {
	*x = GetConnectionStatsResponse{}
	mi := &file_sync_v1_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionStatsResponse) ProtoMessage() {}

func (x *GetConnectionStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionStatsResponse.ProtoReflect.Descriptor instead.
func (*GetConnectionStatsResponse) Descriptor() ([]byte, []int) {
	return file_sync_v1_sync_proto_rawDescGZIP(), []int{7}
}

func (x *GetConnectionStatsResponse) GetTotalConnections() int32 {
	if x != nil {
		return x.TotalConnections
	}
	return 0
}

func (x *GetConnectionStatsResponse) GetUniqueUsers() int32 {
	if x != nil {
		return x.UniqueUsers
	}
	return 0
}

func (x *GetConnectionStatsResponse) GetPlatformStats() []*PlatformStats {
	if x != nil {
		return x.PlatformStats
	}
	return nil
}

func (x *GetConnectionStatsResponse) GetUserConnections() []*UserConnection {
	if x != nil {
		return x.UserConnections
	}
	return nil
}

// BroadcastSystemMessageRequest sends a system-wide message.
type BroadcastSystemMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Message type (e.g., "maintenance", "announcement")
	MessageType string `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	// Message payload
	Data *structpb.Struct `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Optional: only send to specific user roles
	TargetRoles   []string `protobuf:"bytes,3,rep,name=target_roles,json=targetRoles,proto3" json:"target_roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastSystemMessageRequest) Reset() {
	*x = BroadcastSystemMessageRequest{}
	mi := &file_sync_v1_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastSystemMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastSystemMessageRequest) ProtoMessage() {}

func (x *BroadcastSystemMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastSystemMessageRequest.ProtoReflect.Descriptor instead.
func (*BroadcastSystemMessageRequest) Descriptor() ([]byte, []int) {
	return file_sync_v1_sync_proto_rawDescGZIP(), []int{8}
}

func (x *BroadcastSystemMessageRequest) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *BroadcastSystemMessageRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BroadcastSystemMessageRequest) GetTargetRoles() []string {
	if x != nil {
		return x.TargetRoles
	}
	return nil
}

// BroadcastSystemMessageResponse confirms the broadcast.
type BroadcastSystemMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the broadcast was successful
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Number of users notified
	UsersNotified int32 `protobuf:"varint,2,opt,name=users_notified,json=usersNotified,proto3" json:"users_notified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastSystemMessageResponse) Reset() {
	*x = BroadcastSystemMessageResponse{}
	mi := &file_sync_v1_sync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastSystemMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastSystemMessageResponse) ProtoMessage() {}

func (x *BroadcastSystemMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_sync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastSystemMessageResponse.ProtoReflect.Descriptor instead.
func (*BroadcastSystemMessageResponse) Descriptor() ([]byte, []int) {
	return file_sync_v1_sync_proto_rawDescGZIP(), []int{9}
}

func (x *BroadcastSystemMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BroadcastSystemMessageResponse) GetUsersNotified() int32 {
	if x != nil {
		return x.UsersNotified
	}
	return 0
}

// SyncMessage represents a synchronization event.
type SyncMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique message ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Event type (e.g., "favorite.added", "playlist.updated")
	EventType string `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// User ID this message belongs to
	UserId string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Event payload
	Data *structpb.Struct `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	// ACK token (client must send this back to acknowledge)
	AckToken string `protobuf:"bytes,5,opt,name=ack_token,json=ackToken,proto3" json:"ack_token,omitempty"`
	// Message creation timestamp
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Whether this message requires acknowledgment
	RequiresAck   bool `protobuf:"varint,7,opt,name=requires_ack,json=requiresAck,proto3" json:"requires_ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncMessage) Reset() {
	*x = SyncMessage{}
	mi := &file_sync_v1_sync_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMessage) ProtoMessage() {}

func (x *SyncMessage) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_sync_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMessage.ProtoReflect.Descriptor instead.
func (*SyncMessage) Descriptor() ([]byte, []int) {
	return file_sync_v1_sync_proto_rawDescGZIP(), []int{10}
}

func (x *SyncMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SyncMessage) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *SyncMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SyncMessage) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SyncMessage) GetAckToken() string {
	if x != nil {
		return x.AckToken
	}
	return ""
}

func (x *SyncMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SyncMessage) GetRequiresAck() bool {
	if x != nil {
		return x.RequiresAck
	}
	return false
}

// PlatformStats contains connection statistics per platform.
type PlatformStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Platform name (iOS, Android, Web, Desktop, TV)
	Platform string `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	// Number of connections
	ConnectionCount int32 `protobuf:"varint,2,opt,name=connection_count,json=connectionCount,proto3" json:"connection_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlatformStats) Reset() {
	*x = PlatformStats{}
	mi := &file_sync_v1_sync_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformStats) ProtoMessage() {}

func (x *PlatformStats) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_sync_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformStats.ProtoReflect.Descriptor instead.
func (*PlatformStats) Descriptor() ([]byte, []int) {
	return file_sync_v1_sync_proto_rawDescGZIP(), []int{11}
}

func (x *PlatformStats) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *PlatformStats) GetConnectionCount() int32 {
	if x != nil {
		return x.ConnectionCount
	}
	return 0
}

// UserConnection represents a user's WebSocket connection.
type UserConnection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Connection ID
	ConnId string `protobuf:"bytes,1,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	// User ID
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Device ID
	DeviceId string `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Platform
	Platform string `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	// Client IP address
	IpAddress string `protobuf:"bytes,5,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// Connection established time
	ConnectedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	// Last ping time
	LastPing      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_ping,json=lastPing,proto3" json:"last_ping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserConnection) Reset() {
	*x = UserConnection{}
	mi := &file_sync_v1_sync_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserConnection) ProtoMessage() {}

func (x *UserConnection) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_sync_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserConnection.ProtoReflect.Descriptor instead.
func (*UserConnection) Descriptor() ([]byte, []int) {
	return file_sync_v1_sync_proto_rawDescGZIP(), []int{12}
}

func (x *UserConnection) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *UserConnection) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserConnection) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *UserConnection) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *UserConnection) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *UserConnection) GetConnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConnectedAt
	}
	return nil
}

func (x *UserConnection) GetLastPing() *timestamppb.Timestamp {
	if x != nil {
		return x.LastPing
	}
	return nil
}

var File_sync_v1_sync_proto protoreflect.FileDescriptor

const file_sync_v1_sync_proto_rawDesc = "" +
	"\n" +
	"\x12sync/v1/sync.proto\x12\async.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xcf\x01\n" +
	"\x12TriggerSyncRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04data\x12*\n" +
	"\x11exclude_device_id\x18\x04 \x01(\tR\x0fexcludeDeviceId\x12(\n" +
	"\x10queue_if_offline\x18\x05 \x01(\bR\x0equeueIfOffline\"r\n" +
	"\x13TriggerSyncResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12)\n" +
	"\x10devices_notified\x18\x02 \x01(\x05R\x0fdevicesNotified\x12\x16\n" +
	"\x06queued\x18\x03 \x01(\bR\x06queued\"t\n" +
	"\x19GetOfflineMessagesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12(\n" +
	"\x10after_message_id\x18\x02 \x01(\tR\x0eafterMessageId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"i\n" +
	"\x1aGetOfflineMessagesResponse\x120\n" +
	"\bmessages\x18\x01 \x03(\v2\x14.sync.v1.SyncMessageR\bmessages\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"h\n" +
	"\x11AckMessageRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tack_token\x18\x03 \x01(\tR\backToken\".\n" +
	"\x12AckMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"4\n" +
	"\x19GetConnectionStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xef\x01\n" +
	"\x1aGetConnectionStatsResponse\x12+\n" +
	"\x11total_connections\x18\x01 \x01(\x05R\x10totalConnections\x12!\n" +
	"\funique_users\x18\x02 \x01(\x05R\vuniqueUsers\x12=\n" +
	"\x0eplatform_stats\x18\x03 \x03(\v2\x16.sync.v1.PlatformStatsR\rplatformStats\x12B\n" +
	"\x10user_connections\x18\x04 \x03(\v2\x17.sync.v1.UserConnectionR\x0fuserConnections\"\x92\x01\n" +
	"\x1dBroadcastSystemMessageRequest\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04data\x12!\n" +
	"\ftarget_roles\x18\x03 \x03(\tR\vtargetRoles\"a\n" +
	"\x1eBroadcastSystemMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0eusers_notified\x18\x02 \x01(\x05R\rusersNotified\"\xfd\x01\n" +
	"\vSyncMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12+\n" +
	"\x04data\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x04data\x12\x1b\n" +
	"\tack_token\x18\x05 \x01(\tR\backToken\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12!\n" +
	"\frequires_ack\x18\a \x01(\bR\vrequiresAck\"V\n" +
	"\rPlatformStats\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12)\n" +
	"\x10connection_count\x18\x02 \x01(\x05R\x0fconnectionCount\"\x92\x02\n" +
	"\x0eUserConnection\x12\x17\n" +
	"\aconn_id\x18\x01 \x01(\tR\x06connId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x05 \x01(\tR\tipAddress\x12=\n" +
	"\fconnected_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vconnectedAt\x127\n" +
	"\tlast_ping\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\blastPing2\xc7\x03\n" +
	"\vSyncService\x12H\n" +
	"\vTriggerSync\x12\x1b.sync.v1.TriggerSyncRequest\x1a\x1c.sync.v1.TriggerSyncResponse\x12]\n" +
	"\x12GetOfflineMessages\x12\".sync.v1.GetOfflineMessagesRequest\x1a#.sync.v1.GetOfflineMessagesResponse\x12E\n" +
	"\n" +
	"AckMessage\x12\x1a.sync.v1.AckMessageRequest\x1a\x1b.sync.v1.AckMessageResponse\x12]\n" +
	"\x12GetConnectionStats\x12\".sync.v1.GetConnectionStatsRequest\x1a#.sync.v1.GetConnectionStatsResponse\x12i\n" +
	"\x16BroadcastSystemMessage\x12&.sync.v1.BroadcastSystemMessageRequest\x1a'.sync.v1.BroadcastSystemMessageResponseB=Z;github.com/xiaoxiao0301/listen-stream-v2/server/shared/proto/sync/v1;syncv1b\x06proto3"

var (
	file_sync_v1_sync_proto_rawDescOnce sync.Once
	file_sync_v1_sync_proto_rawDescData []byte
)

func file_sync_v1_sync_proto_rawDescGZIP() []byte {
	file_sync_v1_sync_proto_rawDescOnce.Do(func() {
		file_sync_v1_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sync_v1_sync_proto_rawDesc), len(file_sync_v1_sync_proto_rawDesc)))
	})
	return file_sync_v1_sync_proto_rawDescData
}

var file_sync_v1_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_sync_v1_sync_proto_goTypes = []any{
	(*TriggerSyncRequest)(nil),             // 0: sync.v1.TriggerSyncRequest
	(*TriggerSyncResponse)(nil),            // 1: sync.v1.TriggerSyncResponse
	(*GetOfflineMessagesRequest)(nil),      // 2: sync.v1.GetOfflineMessagesRequest
	(*GetOfflineMessagesResponse)(nil),     // 3: sync.v1.GetOfflineMessagesResponse
	(*AckMessageRequest)(nil),              // 4: sync.v1.AckMessageRequest
	(*AckMessageResponse)(nil),             // 5: sync.v1.AckMessageResponse
	(*GetConnectionStatsRequest)(nil),      // 6: sync.v1.GetConnectionStatsRequest
	(*GetConnectionStatsResponse)(nil),     // 7: sync.v1.GetConnectionStatsResponse
	(*BroadcastSystemMessageRequest)(nil),  // 8: sync.v1.BroadcastSystemMessageRequest
	(*BroadcastSystemMessageResponse)(nil), // 9: sync.v1.BroadcastSystemMessageResponse
	(*SyncMessage)(nil),                    // 10: sync.v1.SyncMessage
	(*PlatformStats)(nil),                  // 11: sync.v1.PlatformStats
	(*UserConnection)(nil),                 // 12: sync.v1.UserConnection
	(*structpb.Struct)(nil),                // 13: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),          // 14: google.protobuf.Timestamp
}
var file_sync_v1_sync_proto_depIdxs = []int32{
	13, // 0: sync.v1.TriggerSyncRequest.data:type_name -> google.protobuf.Struct
	10, // 1: sync.v1.GetOfflineMessagesResponse.messages:type_name -> sync.v1.SyncMessage
	11, // 2: sync.v1.GetConnectionStatsResponse.platform_stats:type_name -> sync.v1.PlatformStats
	12, // 3: sync.v1.GetConnectionStatsResponse.user_connections:type_name -> sync.v1.UserConnection
	13, // 4: sync.v1.BroadcastSystemMessageRequest.data:type_name -> google.protobuf.Struct
	13, // 5: sync.v1.SyncMessage.data:type_name -> google.protobuf.Struct
	14, // 6: sync.v1.SyncMessage.created_at:type_name -> google.protobuf.Timestamp
	14, // 7: sync.v1.UserConnection.connected_at:type_name -> google.protobuf.Timestamp
	14, // 8: sync.v1.UserConnection.last_ping:type_name -> google.protobuf.Timestamp
	0,  // 9: sync.v1.SyncService.TriggerSync:input_type -> sync.v1.TriggerSyncRequest
	2,  // 10: sync.v1.SyncService.GetOfflineMessages:input_type -> sync.v1.GetOfflineMessagesRequest
	4,  // 11: sync.v1.SyncService.AckMessage:input_type -> sync.v1.AckMessageRequest
	6,  // 12: sync.v1.SyncService.GetConnectionStats:input_type -> sync.v1.GetConnectionStatsRequest
	8,  // 13: sync.v1.SyncService.BroadcastSystemMessage:input_type -> sync.v1.BroadcastSystemMessageRequest
	1,  // 14: sync.v1.SyncService.TriggerSync:output_type -> sync.v1.TriggerSyncResponse
	3,  // 15: sync.v1.SyncService.GetOfflineMessages:output_type -> sync.v1.GetOfflineMessagesResponse
	5,  // 16: sync.v1.SyncService.AckMessage:output_type -> sync.v1.AckMessageResponse
	7,  // 17: sync.v1.SyncService.GetConnectionStats:output_type -> sync.v1.GetConnectionStatsResponse
	9,  // 18: sync.v1.SyncService.BroadcastSystemMessage:output_type -> sync.v1.BroadcastSystemMessageResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_sync_v1_sync_proto_init() }
func file_sync_v1_sync_proto_init() {
	if File_sync_v1_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_v1_sync_proto_rawDesc), len(file_sync_v1_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sync_v1_sync_proto_goTypes,
		DependencyIndexes: file_sync_v1_sync_proto_depIdxs,
		MessageInfos:      file_sync_v1_sync_proto_msgTypes,
	}.Build()
	File_sync_v1_sync_proto = out.File
	file_sync_v1_sync_proto_goTypes = nil
	file_sync_v1_sync_proto_depIdxs = nil
}
