// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: user/v1/user.proto

package userv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_AddFavorite_FullMethodName            = "/user.v1.UserService/AddFavorite"
	UserService_RemoveFavorite_FullMethodName         = "/user.v1.UserService/RemoveFavorite"
	UserService_ListFavorites_FullMethodName          = "/user.v1.UserService/ListFavorites"
	UserService_AddPlayHistory_FullMethodName         = "/user.v1.UserService/AddPlayHistory"
	UserService_ListPlayHistory_FullMethodName        = "/user.v1.UserService/ListPlayHistory"
	UserService_CreatePlaylist_FullMethodName         = "/user.v1.UserService/CreatePlaylist"
	UserService_UpdatePlaylist_FullMethodName         = "/user.v1.UserService/UpdatePlaylist"
	UserService_DeletePlaylist_FullMethodName         = "/user.v1.UserService/DeletePlaylist"
	UserService_ListPlaylists_FullMethodName          = "/user.v1.UserService/ListPlaylists"
	UserService_AddSongToPlaylist_FullMethodName      = "/user.v1.UserService/AddSongToPlaylist"
	UserService_RemoveSongFromPlaylist_FullMethodName = "/user.v1.UserService/RemoveSongFromPlaylist"
	UserService_GetPlaylistSongs_FullMethodName       = "/user.v1.UserService/GetPlaylistSongs"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// UserService manages user-generated content including favorites, playlists, and play history.
//
// All RPCs require valid authentication and are called by proxy-svc.
type UserServiceClient interface {
	// AddFavorite adds a song/album/artist/mv to user's favorites.
	AddFavorite(ctx context.Context, in *AddFavoriteRequest, opts ...grpc.CallOption) (*AddFavoriteResponse, error)
	// RemoveFavorite removes an item from favorites (soft delete).
	RemoveFavorite(ctx context.Context, in *RemoveFavoriteRequest, opts ...grpc.CallOption) (*RemoveFavoriteResponse, error)
	// ListFavorites returns paginated favorites for a user.
	ListFavorites(ctx context.Context, in *ListFavoritesRequest, opts ...grpc.CallOption) (*ListFavoritesResponse, error)
	// AddPlayHistory records a song play event.
	//
	// Automatically enforces 500-item limit per user with FIFO eviction.
	AddPlayHistory(ctx context.Context, in *AddPlayHistoryRequest, opts ...grpc.CallOption) (*AddPlayHistoryResponse, error)
	// ListPlayHistory returns paginated play history.
	ListPlayHistory(ctx context.Context, in *ListPlayHistoryRequest, opts ...grpc.CallOption) (*ListPlayHistoryResponse, error)
	// CreatePlaylist creates a new user playlist.
	CreatePlaylist(ctx context.Context, in *CreatePlaylistRequest, opts ...grpc.CallOption) (*CreatePlaylistResponse, error)
	// UpdatePlaylist modifies playlist metadata (name, cover, visibility).
	UpdatePlaylist(ctx context.Context, in *UpdatePlaylistRequest, opts ...grpc.CallOption) (*UpdatePlaylistResponse, error)
	// DeletePlaylist soft-deletes a playlist.
	DeletePlaylist(ctx context.Context, in *DeletePlaylistRequest, opts ...grpc.CallOption) (*DeletePlaylistResponse, error)
	// ListPlaylists returns all playlists for a user.
	ListPlaylists(ctx context.Context, in *ListPlaylistsRequest, opts ...grpc.CallOption) (*ListPlaylistsResponse, error)
	// AddSongToPlaylist adds a song to a playlist.
	AddSongToPlaylist(ctx context.Context, in *AddSongToPlaylistRequest, opts ...grpc.CallOption) (*AddSongToPlaylistResponse, error)
	// RemoveSongFromPlaylist removes a song from a playlist.
	RemoveSongFromPlaylist(ctx context.Context, in *RemoveSongFromPlaylistRequest, opts ...grpc.CallOption) (*RemoveSongFromPlaylistResponse, error)
	// GetPlaylistSongs returns all songs in a playlist.
	GetPlaylistSongs(ctx context.Context, in *GetPlaylistSongsRequest, opts ...grpc.CallOption) (*GetPlaylistSongsResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) AddFavorite(ctx context.Context, in *AddFavoriteRequest, opts ...grpc.CallOption) (*AddFavoriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddFavoriteResponse)
	err := c.cc.Invoke(ctx, UserService_AddFavorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RemoveFavorite(ctx context.Context, in *RemoveFavoriteRequest, opts ...grpc.CallOption) (*RemoveFavoriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveFavoriteResponse)
	err := c.cc.Invoke(ctx, UserService_RemoveFavorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListFavorites(ctx context.Context, in *ListFavoritesRequest, opts ...grpc.CallOption) (*ListFavoritesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFavoritesResponse)
	err := c.cc.Invoke(ctx, UserService_ListFavorites_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AddPlayHistory(ctx context.Context, in *AddPlayHistoryRequest, opts ...grpc.CallOption) (*AddPlayHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPlayHistoryResponse)
	err := c.cc.Invoke(ctx, UserService_AddPlayHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListPlayHistory(ctx context.Context, in *ListPlayHistoryRequest, opts ...grpc.CallOption) (*ListPlayHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPlayHistoryResponse)
	err := c.cc.Invoke(ctx, UserService_ListPlayHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreatePlaylist(ctx context.Context, in *CreatePlaylistRequest, opts ...grpc.CallOption) (*CreatePlaylistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePlaylistResponse)
	err := c.cc.Invoke(ctx, UserService_CreatePlaylist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdatePlaylist(ctx context.Context, in *UpdatePlaylistRequest, opts ...grpc.CallOption) (*UpdatePlaylistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePlaylistResponse)
	err := c.cc.Invoke(ctx, UserService_UpdatePlaylist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeletePlaylist(ctx context.Context, in *DeletePlaylistRequest, opts ...grpc.CallOption) (*DeletePlaylistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePlaylistResponse)
	err := c.cc.Invoke(ctx, UserService_DeletePlaylist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListPlaylists(ctx context.Context, in *ListPlaylistsRequest, opts ...grpc.CallOption) (*ListPlaylistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPlaylistsResponse)
	err := c.cc.Invoke(ctx, UserService_ListPlaylists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AddSongToPlaylist(ctx context.Context, in *AddSongToPlaylistRequest, opts ...grpc.CallOption) (*AddSongToPlaylistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddSongToPlaylistResponse)
	err := c.cc.Invoke(ctx, UserService_AddSongToPlaylist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RemoveSongFromPlaylist(ctx context.Context, in *RemoveSongFromPlaylistRequest, opts ...grpc.CallOption) (*RemoveSongFromPlaylistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveSongFromPlaylistResponse)
	err := c.cc.Invoke(ctx, UserService_RemoveSongFromPlaylist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetPlaylistSongs(ctx context.Context, in *GetPlaylistSongsRequest, opts ...grpc.CallOption) (*GetPlaylistSongsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlaylistSongsResponse)
	err := c.cc.Invoke(ctx, UserService_GetPlaylistSongs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
//
// UserService manages user-generated content including favorites, playlists, and play history.
//
// All RPCs require valid authentication and are called by proxy-svc.
type UserServiceServer interface {
	// AddFavorite adds a song/album/artist/mv to user's favorites.
	AddFavorite(context.Context, *AddFavoriteRequest) (*AddFavoriteResponse, error)
	// RemoveFavorite removes an item from favorites (soft delete).
	RemoveFavorite(context.Context, *RemoveFavoriteRequest) (*RemoveFavoriteResponse, error)
	// ListFavorites returns paginated favorites for a user.
	ListFavorites(context.Context, *ListFavoritesRequest) (*ListFavoritesResponse, error)
	// AddPlayHistory records a song play event.
	//
	// Automatically enforces 500-item limit per user with FIFO eviction.
	AddPlayHistory(context.Context, *AddPlayHistoryRequest) (*AddPlayHistoryResponse, error)
	// ListPlayHistory returns paginated play history.
	ListPlayHistory(context.Context, *ListPlayHistoryRequest) (*ListPlayHistoryResponse, error)
	// CreatePlaylist creates a new user playlist.
	CreatePlaylist(context.Context, *CreatePlaylistRequest) (*CreatePlaylistResponse, error)
	// UpdatePlaylist modifies playlist metadata (name, cover, visibility).
	UpdatePlaylist(context.Context, *UpdatePlaylistRequest) (*UpdatePlaylistResponse, error)
	// DeletePlaylist soft-deletes a playlist.
	DeletePlaylist(context.Context, *DeletePlaylistRequest) (*DeletePlaylistResponse, error)
	// ListPlaylists returns all playlists for a user.
	ListPlaylists(context.Context, *ListPlaylistsRequest) (*ListPlaylistsResponse, error)
	// AddSongToPlaylist adds a song to a playlist.
	AddSongToPlaylist(context.Context, *AddSongToPlaylistRequest) (*AddSongToPlaylistResponse, error)
	// RemoveSongFromPlaylist removes a song from a playlist.
	RemoveSongFromPlaylist(context.Context, *RemoveSongFromPlaylistRequest) (*RemoveSongFromPlaylistResponse, error)
	// GetPlaylistSongs returns all songs in a playlist.
	GetPlaylistSongs(context.Context, *GetPlaylistSongsRequest) (*GetPlaylistSongsResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) AddFavorite(context.Context, *AddFavoriteRequest) (*AddFavoriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddFavorite not implemented")
}
func (UnimplementedUserServiceServer) RemoveFavorite(context.Context, *RemoveFavoriteRequest) (*RemoveFavoriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveFavorite not implemented")
}
func (UnimplementedUserServiceServer) ListFavorites(context.Context, *ListFavoritesRequest) (*ListFavoritesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFavorites not implemented")
}
func (UnimplementedUserServiceServer) AddPlayHistory(context.Context, *AddPlayHistoryRequest) (*AddPlayHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddPlayHistory not implemented")
}
func (UnimplementedUserServiceServer) ListPlayHistory(context.Context, *ListPlayHistoryRequest) (*ListPlayHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlayHistory not implemented")
}
func (UnimplementedUserServiceServer) CreatePlaylist(context.Context, *CreatePlaylistRequest) (*CreatePlaylistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePlaylist not implemented")
}
func (UnimplementedUserServiceServer) UpdatePlaylist(context.Context, *UpdatePlaylistRequest) (*UpdatePlaylistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePlaylist not implemented")
}
func (UnimplementedUserServiceServer) DeletePlaylist(context.Context, *DeletePlaylistRequest) (*DeletePlaylistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePlaylist not implemented")
}
func (UnimplementedUserServiceServer) ListPlaylists(context.Context, *ListPlaylistsRequest) (*ListPlaylistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlaylists not implemented")
}
func (UnimplementedUserServiceServer) AddSongToPlaylist(context.Context, *AddSongToPlaylistRequest) (*AddSongToPlaylistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddSongToPlaylist not implemented")
}
func (UnimplementedUserServiceServer) RemoveSongFromPlaylist(context.Context, *RemoveSongFromPlaylistRequest) (*RemoveSongFromPlaylistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveSongFromPlaylist not implemented")
}
func (UnimplementedUserServiceServer) GetPlaylistSongs(context.Context, *GetPlaylistSongsRequest) (*GetPlaylistSongsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlaylistSongs not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call panics, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_AddFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFavoriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_AddFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddFavorite(ctx, req.(*AddFavoriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RemoveFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFavoriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RemoveFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_RemoveFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RemoveFavorite(ctx, req.(*RemoveFavoriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListFavorites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFavoritesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListFavorites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ListFavorites_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListFavorites(ctx, req.(*ListFavoritesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AddPlayHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPlayHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddPlayHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_AddPlayHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddPlayHistory(ctx, req.(*AddPlayHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListPlayHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlayHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListPlayHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ListPlayHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListPlayHistory(ctx, req.(*ListPlayHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreatePlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlaylistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreatePlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CreatePlaylist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreatePlaylist(ctx, req.(*CreatePlaylistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdatePlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePlaylistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdatePlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdatePlaylist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdatePlaylist(ctx, req.(*UpdatePlaylistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeletePlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePlaylistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeletePlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_DeletePlaylist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeletePlaylist(ctx, req.(*DeletePlaylistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListPlaylists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlaylistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListPlaylists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ListPlaylists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListPlaylists(ctx, req.(*ListPlaylistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AddSongToPlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSongToPlaylistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddSongToPlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_AddSongToPlaylist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddSongToPlaylist(ctx, req.(*AddSongToPlaylistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RemoveSongFromPlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSongFromPlaylistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RemoveSongFromPlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_RemoveSongFromPlaylist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RemoveSongFromPlaylist(ctx, req.(*RemoveSongFromPlaylistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetPlaylistSongs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlaylistSongsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetPlaylistSongs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetPlaylistSongs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetPlaylistSongs(ctx, req.(*GetPlaylistSongsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.v1.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddFavorite",
			Handler:    _UserService_AddFavorite_Handler,
		},
		{
			MethodName: "RemoveFavorite",
			Handler:    _UserService_RemoveFavorite_Handler,
		},
		{
			MethodName: "ListFavorites",
			Handler:    _UserService_ListFavorites_Handler,
		},
		{
			MethodName: "AddPlayHistory",
			Handler:    _UserService_AddPlayHistory_Handler,
		},
		{
			MethodName: "ListPlayHistory",
			Handler:    _UserService_ListPlayHistory_Handler,
		},
		{
			MethodName: "CreatePlaylist",
			Handler:    _UserService_CreatePlaylist_Handler,
		},
		{
			MethodName: "UpdatePlaylist",
			Handler:    _UserService_UpdatePlaylist_Handler,
		},
		{
			MethodName: "DeletePlaylist",
			Handler:    _UserService_DeletePlaylist_Handler,
		},
		{
			MethodName: "ListPlaylists",
			Handler:    _UserService_ListPlaylists_Handler,
		},
		{
			MethodName: "AddSongToPlaylist",
			Handler:    _UserService_AddSongToPlaylist_Handler,
		},
		{
			MethodName: "RemoveSongFromPlaylist",
			Handler:    _UserService_RemoveSongFromPlaylist_Handler,
		},
		{
			MethodName: "GetPlaylistSongs",
			Handler:    _UserService_GetPlaylistSongs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/v1/user.proto",
}
