// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: user/v1/user.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FavoriteType defines what can be favorited.
type FavoriteType int32

const (
	// Default type (should not be used)
	FavoriteType_FAVORITE_TYPE_UNSPECIFIED FavoriteType = 0
	// Song
	FavoriteType_FAVORITE_TYPE_SONG FavoriteType = 1
	// Album
	FavoriteType_FAVORITE_TYPE_ALBUM FavoriteType = 2
	// Artist
	FavoriteType_FAVORITE_TYPE_ARTIST FavoriteType = 3
	// Music video
	FavoriteType_FAVORITE_TYPE_MV FavoriteType = 4
)

// Enum value maps for FavoriteType.
var (
	FavoriteType_name = map[int32]string{
		0: "FAVORITE_TYPE_UNSPECIFIED",
		1: "FAVORITE_TYPE_SONG",
		2: "FAVORITE_TYPE_ALBUM",
		3: "FAVORITE_TYPE_ARTIST",
		4: "FAVORITE_TYPE_MV",
	}
	FavoriteType_value = map[string]int32{
		"FAVORITE_TYPE_UNSPECIFIED": 0,
		"FAVORITE_TYPE_SONG":        1,
		"FAVORITE_TYPE_ALBUM":       2,
		"FAVORITE_TYPE_ARTIST":      3,
		"FAVORITE_TYPE_MV":          4,
	}
)

func (x FavoriteType) Enum() *FavoriteType {
	p := new(FavoriteType)
	*p = x
	return p
}

func (x FavoriteType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FavoriteType) Descriptor() protoreflect.EnumDescriptor {
	return file_user_v1_user_proto_enumTypes[0].Descriptor()
}

func (FavoriteType) Type() protoreflect.EnumType {
	return &file_user_v1_user_proto_enumTypes[0]
}

func (x FavoriteType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FavoriteType.Descriptor instead.
func (FavoriteType) EnumDescriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{0}
}

// AddFavoriteRequest specifies the item to favorite.
type AddFavoriteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Type of content to favorite
	Type FavoriteType `protobuf:"varint,2,opt,name=type,proto3,enum=user.v1.FavoriteType" json:"type,omitempty"`
	// Target content ID (third-party platform ID)
	TargetId string `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	// Optional metadata for display (redundant storage for offline)
	Metadata      *FavoriteMetadata `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFavoriteRequest) Reset() {
	*x = AddFavoriteRequest{}
	mi := &file_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFavoriteRequest) ProtoMessage() {}

func (x *AddFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFavoriteRequest.ProtoReflect.Descriptor instead.
func (*AddFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *AddFavoriteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddFavoriteRequest) GetType() FavoriteType {
	if x != nil {
		return x.Type
	}
	return FavoriteType_FAVORITE_TYPE_UNSPECIFIED
}

func (x *AddFavoriteRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *AddFavoriteRequest) GetMetadata() *FavoriteMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// AddFavoriteResponse confirms the favorite was added.
type AddFavoriteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The created favorite ID
	FavoriteId string `protobuf:"bytes,1,opt,name=favorite_id,json=favoriteId,proto3" json:"favorite_id,omitempty"`
	// Creation timestamp
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFavoriteResponse) Reset() {
	*x = AddFavoriteResponse{}
	mi := &file_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFavoriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFavoriteResponse) ProtoMessage() {}

func (x *AddFavoriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFavoriteResponse.ProtoReflect.Descriptor instead.
func (*AddFavoriteResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *AddFavoriteResponse) GetFavoriteId() string {
	if x != nil {
		return x.FavoriteId
	}
	return ""
}

func (x *AddFavoriteResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// RemoveFavoriteRequest specifies which favorite to remove.
type RemoveFavoriteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Favorite ID to remove
	FavoriteId    string `protobuf:"bytes,2,opt,name=favorite_id,json=favoriteId,proto3" json:"favorite_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFavoriteRequest) Reset() {
	*x = RemoveFavoriteRequest{}
	mi := &file_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFavoriteRequest) ProtoMessage() {}

func (x *RemoveFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFavoriteRequest.ProtoReflect.Descriptor instead.
func (*RemoveFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveFavoriteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveFavoriteRequest) GetFavoriteId() string {
	if x != nil {
		return x.FavoriteId
	}
	return ""
}

// RemoveFavoriteResponse confirms the removal.
type RemoveFavoriteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the removal was successful
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFavoriteResponse) Reset() {
	*x = RemoveFavoriteResponse{}
	mi := &file_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFavoriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFavoriteResponse) ProtoMessage() {}

func (x *RemoveFavoriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFavoriteResponse.ProtoReflect.Descriptor instead.
func (*RemoveFavoriteResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveFavoriteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ListFavoritesRequest specifies pagination and filtering.
type ListFavoritesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Optional type filter
	Type FavoriteType `protobuf:"varint,2,opt,name=type,proto3,enum=user.v1.FavoriteType" json:"type,omitempty"`
	// Pagination: page number (1-based)
	Page int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	// Pagination: items per page (default: 20, max: 100)
	PageSize      int32 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFavoritesRequest) Reset() {
	*x = ListFavoritesRequest{}
	mi := &file_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFavoritesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFavoritesRequest) ProtoMessage() {}

func (x *ListFavoritesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFavoritesRequest.ProtoReflect.Descriptor instead.
func (*ListFavoritesRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *ListFavoritesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListFavoritesRequest) GetType() FavoriteType {
	if x != nil {
		return x.Type
	}
	return FavoriteType_FAVORITE_TYPE_UNSPECIFIED
}

func (x *ListFavoritesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFavoritesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ListFavoritesResponse contains paginated favorites.
type ListFavoritesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of favorites
	Favorites []*Favorite `protobuf:"bytes,1,rep,name=favorites,proto3" json:"favorites,omitempty"`
	// Total count (for pagination UI)
	Total int32 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	// Current page
	Page int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	// Page size
	PageSize      int32 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFavoritesResponse) Reset() {
	*x = ListFavoritesResponse{}
	mi := &file_user_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFavoritesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFavoritesResponse) ProtoMessage() {}

func (x *ListFavoritesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFavoritesResponse.ProtoReflect.Descriptor instead.
func (*ListFavoritesResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *ListFavoritesResponse) GetFavorites() []*Favorite {
	if x != nil {
		return x.Favorites
	}
	return nil
}

func (x *ListFavoritesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListFavoritesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFavoritesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// AddPlayHistoryRequest records a play event.
type AddPlayHistoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Song ID (third-party platform ID)
	SongId string `protobuf:"bytes,2,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
	// Song name (redundant storage for offline display)
	SongName string `protobuf:"bytes,3,opt,name=song_name,json=songName,proto3" json:"song_name,omitempty"`
	// Artist name (redundant storage)
	ArtistName string `protobuf:"bytes,4,opt,name=artist_name,json=artistName,proto3" json:"artist_name,omitempty"`
	// Album name (redundant storage)
	AlbumName string `protobuf:"bytes,5,opt,name=album_name,json=albumName,proto3" json:"album_name,omitempty"`
	// Play duration in seconds
	Duration      int32 `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPlayHistoryRequest) Reset() {
	*x = AddPlayHistoryRequest{}
	mi := &file_user_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPlayHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPlayHistoryRequest) ProtoMessage() {}

func (x *AddPlayHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPlayHistoryRequest.ProtoReflect.Descriptor instead.
func (*AddPlayHistoryRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *AddPlayHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddPlayHistoryRequest) GetSongId() string {
	if x != nil {
		return x.SongId
	}
	return ""
}

func (x *AddPlayHistoryRequest) GetSongName() string {
	if x != nil {
		return x.SongName
	}
	return ""
}

func (x *AddPlayHistoryRequest) GetArtistName() string {
	if x != nil {
		return x.ArtistName
	}
	return ""
}

func (x *AddPlayHistoryRequest) GetAlbumName() string {
	if x != nil {
		return x.AlbumName
	}
	return ""
}

func (x *AddPlayHistoryRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

// AddPlayHistoryResponse confirms the history was recorded.
type AddPlayHistoryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The created history ID
	HistoryId string `protobuf:"bytes,1,opt,name=history_id,json=historyId,proto3" json:"history_id,omitempty"`
	// Play timestamp
	PlayedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=played_at,json=playedAt,proto3" json:"played_at,omitempty"`
	// Whether old history was evicted (due to 500-item limit)
	EvictedOldHistory bool `protobuf:"varint,3,opt,name=evicted_old_history,json=evictedOldHistory,proto3" json:"evicted_old_history,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AddPlayHistoryResponse) Reset() {
	*x = AddPlayHistoryResponse{}
	mi := &file_user_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPlayHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPlayHistoryResponse) ProtoMessage() {}

func (x *AddPlayHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPlayHistoryResponse.ProtoReflect.Descriptor instead.
func (*AddPlayHistoryResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *AddPlayHistoryResponse) GetHistoryId() string {
	if x != nil {
		return x.HistoryId
	}
	return ""
}

func (x *AddPlayHistoryResponse) GetPlayedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PlayedAt
	}
	return nil
}

func (x *AddPlayHistoryResponse) GetEvictedOldHistory() bool {
	if x != nil {
		return x.EvictedOldHistory
	}
	return false
}

// ListPlayHistoryRequest specifies pagination.
type ListPlayHistoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Pagination: page number (1-based)
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	// Pagination: items per page (default: 20, max: 100)
	PageSize      int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlayHistoryRequest) Reset() {
	*x = ListPlayHistoryRequest{}
	mi := &file_user_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlayHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlayHistoryRequest) ProtoMessage() {}

func (x *ListPlayHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlayHistoryRequest.ProtoReflect.Descriptor instead.
func (*ListPlayHistoryRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *ListPlayHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListPlayHistoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPlayHistoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ListPlayHistoryResponse contains paginated history.
type ListPlayHistoryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of play history (newest first)
	History []*PlayHistory `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	// Total count (max 500)
	Total int32 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	// Current page
	Page int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	// Page size
	PageSize      int32 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlayHistoryResponse) Reset() {
	*x = ListPlayHistoryResponse{}
	mi := &file_user_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlayHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlayHistoryResponse) ProtoMessage() {}

func (x *ListPlayHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlayHistoryResponse.ProtoReflect.Descriptor instead.
func (*ListPlayHistoryResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *ListPlayHistoryResponse) GetHistory() []*PlayHistory {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *ListPlayHistoryResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListPlayHistoryResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPlayHistoryResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// CreatePlaylistRequest contains playlist details.
type CreatePlaylistRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Playlist name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Optional cover image URL
	CoverUrl string `protobuf:"bytes,3,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	// Whether the playlist is public
	IsPublic      bool `protobuf:"varint,4,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlaylistRequest) Reset() {
	*x = CreatePlaylistRequest{}
	mi := &file_user_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlaylistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaylistRequest) ProtoMessage() {}

func (x *CreatePlaylistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaylistRequest.ProtoReflect.Descriptor instead.
func (*CreatePlaylistRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *CreatePlaylistRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePlaylistRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePlaylistRequest) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *CreatePlaylistRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

// CreatePlaylistResponse contains the created playlist.
type CreatePlaylistResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The created playlist
	Playlist      *Playlist `protobuf:"bytes,1,opt,name=playlist,proto3" json:"playlist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlaylistResponse) Reset() {
	*x = CreatePlaylistResponse{}
	mi := &file_user_v1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlaylistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaylistResponse) ProtoMessage() {}

func (x *CreatePlaylistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaylistResponse.ProtoReflect.Descriptor instead.
func (*CreatePlaylistResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{11}
}

func (x *CreatePlaylistResponse) GetPlaylist() *Playlist {
	if x != nil {
		return x.Playlist
	}
	return nil
}

// UpdatePlaylistRequest modifies playlist metadata.
type UpdatePlaylistRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID (for authorization)
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Playlist ID to update
	PlaylistId string `protobuf:"bytes,2,opt,name=playlist_id,json=playlistId,proto3" json:"playlist_id,omitempty"`
	// New name (optional, empty = no change)
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// New cover URL (optional, empty = no change)
	CoverUrl string `protobuf:"bytes,4,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	// New visibility (optional)
	IsPublic      *bool `protobuf:"varint,5,opt,name=is_public,json=isPublic,proto3,oneof" json:"is_public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlaylistRequest) Reset() {
	*x = UpdatePlaylistRequest{}
	mi := &file_user_v1_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlaylistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlaylistRequest) ProtoMessage() {}

func (x *UpdatePlaylistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlaylistRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlaylistRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{12}
}

func (x *UpdatePlaylistRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePlaylistRequest) GetPlaylistId() string {
	if x != nil {
		return x.PlaylistId
	}
	return ""
}

func (x *UpdatePlaylistRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePlaylistRequest) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *UpdatePlaylistRequest) GetIsPublic() bool {
	if x != nil && x.IsPublic != nil {
		return *x.IsPublic
	}
	return false
}

// UpdatePlaylistResponse contains the updated playlist.
type UpdatePlaylistResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The updated playlist
	Playlist      *Playlist `protobuf:"bytes,1,opt,name=playlist,proto3" json:"playlist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlaylistResponse) Reset() {
	*x = UpdatePlaylistResponse{}
	mi := &file_user_v1_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlaylistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlaylistResponse) ProtoMessage() {}

func (x *UpdatePlaylistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlaylistResponse.ProtoReflect.Descriptor instead.
func (*UpdatePlaylistResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{13}
}

func (x *UpdatePlaylistResponse) GetPlaylist() *Playlist {
	if x != nil {
		return x.Playlist
	}
	return nil
}

// DeletePlaylistRequest specifies which playlist to delete.
type DeletePlaylistRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID (for authorization)
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Playlist ID to delete
	PlaylistId    string `protobuf:"bytes,2,opt,name=playlist_id,json=playlistId,proto3" json:"playlist_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePlaylistRequest) Reset() {
	*x = DeletePlaylistRequest{}
	mi := &file_user_v1_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePlaylistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlaylistRequest) ProtoMessage() {}

func (x *DeletePlaylistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlaylistRequest.ProtoReflect.Descriptor instead.
func (*DeletePlaylistRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{14}
}

func (x *DeletePlaylistRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeletePlaylistRequest) GetPlaylistId() string {
	if x != nil {
		return x.PlaylistId
	}
	return ""
}

// DeletePlaylistResponse confirms the deletion.
type DeletePlaylistResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the deletion was successful
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePlaylistResponse) Reset() {
	*x = DeletePlaylistResponse{}
	mi := &file_user_v1_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePlaylistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlaylistResponse) ProtoMessage() {}

func (x *DeletePlaylistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlaylistResponse.ProtoReflect.Descriptor instead.
func (*DeletePlaylistResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{15}
}

func (x *DeletePlaylistResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ListPlaylistsRequest fetches all playlists for a user.
type ListPlaylistsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlaylistsRequest) Reset() {
	*x = ListPlaylistsRequest{}
	mi := &file_user_v1_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlaylistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlaylistsRequest) ProtoMessage() {}

func (x *ListPlaylistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlaylistsRequest.ProtoReflect.Descriptor instead.
func (*ListPlaylistsRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{16}
}

func (x *ListPlaylistsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// ListPlaylistsResponse contains all playlists.
type ListPlaylistsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of playlists
	Playlists     []*Playlist `protobuf:"bytes,1,rep,name=playlists,proto3" json:"playlists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlaylistsResponse) Reset() {
	*x = ListPlaylistsResponse{}
	mi := &file_user_v1_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlaylistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlaylistsResponse) ProtoMessage() {}

func (x *ListPlaylistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlaylistsResponse.ProtoReflect.Descriptor instead.
func (*ListPlaylistsResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{17}
}

func (x *ListPlaylistsResponse) GetPlaylists() []*Playlist {
	if x != nil {
		return x.Playlists
	}
	return nil
}

// AddSongToPlaylistRequest adds a song.
type AddSongToPlaylistRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID (for authorization)
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Playlist ID
	PlaylistId string `protobuf:"bytes,2,opt,name=playlist_id,json=playlistId,proto3" json:"playlist_id,omitempty"`
	// Song ID to add
	SongId string `protobuf:"bytes,3,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
	// Optional position (0 = end, 1+ = specific position)
	Position      int32 `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSongToPlaylistRequest) Reset() {
	*x = AddSongToPlaylistRequest{}
	mi := &file_user_v1_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSongToPlaylistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSongToPlaylistRequest) ProtoMessage() {}

func (x *AddSongToPlaylistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSongToPlaylistRequest.ProtoReflect.Descriptor instead.
func (*AddSongToPlaylistRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{18}
}

func (x *AddSongToPlaylistRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddSongToPlaylistRequest) GetPlaylistId() string {
	if x != nil {
		return x.PlaylistId
	}
	return ""
}

func (x *AddSongToPlaylistRequest) GetSongId() string {
	if x != nil {
		return x.SongId
	}
	return ""
}

func (x *AddSongToPlaylistRequest) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

// AddSongToPlaylistResponse confirms the addition.
type AddSongToPlaylistResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the addition was successful
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// New song count in playlist
	SongCount     int32 `protobuf:"varint,2,opt,name=song_count,json=songCount,proto3" json:"song_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSongToPlaylistResponse) Reset() {
	*x = AddSongToPlaylistResponse{}
	mi := &file_user_v1_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSongToPlaylistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSongToPlaylistResponse) ProtoMessage() {}

func (x *AddSongToPlaylistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSongToPlaylistResponse.ProtoReflect.Descriptor instead.
func (*AddSongToPlaylistResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{19}
}

func (x *AddSongToPlaylistResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddSongToPlaylistResponse) GetSongCount() int32 {
	if x != nil {
		return x.SongCount
	}
	return 0
}

// RemoveSongFromPlaylistRequest removes a song.
type RemoveSongFromPlaylistRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID (for authorization)
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Playlist ID
	PlaylistId string `protobuf:"bytes,2,opt,name=playlist_id,json=playlistId,proto3" json:"playlist_id,omitempty"`
	// Song ID to remove
	SongId        string `protobuf:"bytes,3,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSongFromPlaylistRequest) Reset() {
	*x = RemoveSongFromPlaylistRequest{}
	mi := &file_user_v1_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSongFromPlaylistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSongFromPlaylistRequest) ProtoMessage() {}

func (x *RemoveSongFromPlaylistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSongFromPlaylistRequest.ProtoReflect.Descriptor instead.
func (*RemoveSongFromPlaylistRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{20}
}

func (x *RemoveSongFromPlaylistRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveSongFromPlaylistRequest) GetPlaylistId() string {
	if x != nil {
		return x.PlaylistId
	}
	return ""
}

func (x *RemoveSongFromPlaylistRequest) GetSongId() string {
	if x != nil {
		return x.SongId
	}
	return ""
}

// RemoveSongFromPlaylistResponse confirms the removal.
type RemoveSongFromPlaylistResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the removal was successful
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// New song count in playlist
	SongCount     int32 `protobuf:"varint,2,opt,name=song_count,json=songCount,proto3" json:"song_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSongFromPlaylistResponse) Reset() {
	*x = RemoveSongFromPlaylistResponse{}
	mi := &file_user_v1_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSongFromPlaylistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSongFromPlaylistResponse) ProtoMessage() {}

func (x *RemoveSongFromPlaylistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSongFromPlaylistResponse.ProtoReflect.Descriptor instead.
func (*RemoveSongFromPlaylistResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{21}
}

func (x *RemoveSongFromPlaylistResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveSongFromPlaylistResponse) GetSongCount() int32 {
	if x != nil {
		return x.SongCount
	}
	return 0
}

// GetPlaylistSongsRequest fetches songs in a playlist.
type GetPlaylistSongsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Playlist ID
	PlaylistId    string `protobuf:"bytes,1,opt,name=playlist_id,json=playlistId,proto3" json:"playlist_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlaylistSongsRequest) Reset() {
	*x = GetPlaylistSongsRequest{}
	mi := &file_user_v1_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlaylistSongsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlaylistSongsRequest) ProtoMessage() {}

func (x *GetPlaylistSongsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlaylistSongsRequest.ProtoReflect.Descriptor instead.
func (*GetPlaylistSongsRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{22}
}

func (x *GetPlaylistSongsRequest) GetPlaylistId() string {
	if x != nil {
		return x.PlaylistId
	}
	return ""
}

// GetPlaylistSongsResponse contains playlist songs.
type GetPlaylistSongsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of songs (ordered by position)
	Songs         []*PlaylistSong `protobuf:"bytes,1,rep,name=songs,proto3" json:"songs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlaylistSongsResponse) Reset() {
	*x = GetPlaylistSongsResponse{}
	mi := &file_user_v1_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlaylistSongsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlaylistSongsResponse) ProtoMessage() {}

func (x *GetPlaylistSongsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlaylistSongsResponse.ProtoReflect.Descriptor instead.
func (*GetPlaylistSongsResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{23}
}

func (x *GetPlaylistSongsResponse) GetSongs() []*PlaylistSong {
	if x != nil {
		return x.Songs
	}
	return nil
}

// Favorite represents a favorited item.
type Favorite struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique favorite ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// User ID
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Type of content
	Type FavoriteType `protobuf:"varint,3,opt,name=type,proto3,enum=user.v1.FavoriteType" json:"type,omitempty"`
	// Target content ID
	TargetId string `protobuf:"bytes,4,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	// Optional metadata
	Metadata *FavoriteMetadata `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Creation timestamp
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Favorite) Reset() {
	*x = Favorite{}
	mi := &file_user_v1_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Favorite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Favorite) ProtoMessage() {}

func (x *Favorite) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Favorite.ProtoReflect.Descriptor instead.
func (*Favorite) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{24}
}

func (x *Favorite) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Favorite) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Favorite) GetType() FavoriteType {
	if x != nil {
		return x.Type
	}
	return FavoriteType_FAVORITE_TYPE_UNSPECIFIED
}

func (x *Favorite) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *Favorite) GetMetadata() *FavoriteMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Favorite) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// FavoriteMetadata contains display information.
type FavoriteMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Song/Album/Artist/MV name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Artist name (for songs/albums)
	Artist string `protobuf:"bytes,2,opt,name=artist,proto3" json:"artist,omitempty"`
	// Cover image URL
	CoverUrl      string `protobuf:"bytes,3,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteMetadata) Reset() {
	*x = FavoriteMetadata{}
	mi := &file_user_v1_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteMetadata) ProtoMessage() {}

func (x *FavoriteMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteMetadata.ProtoReflect.Descriptor instead.
func (*FavoriteMetadata) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{25}
}

func (x *FavoriteMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FavoriteMetadata) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *FavoriteMetadata) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

// PlayHistory represents a play event.
type PlayHistory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique history ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// User ID
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Song ID
	SongId string `protobuf:"bytes,3,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
	// Song name (redundant storage)
	SongName string `protobuf:"bytes,4,opt,name=song_name,json=songName,proto3" json:"song_name,omitempty"`
	// Artist name (redundant storage)
	ArtistName string `protobuf:"bytes,5,opt,name=artist_name,json=artistName,proto3" json:"artist_name,omitempty"`
	// Album name (redundant storage)
	AlbumName string `protobuf:"bytes,6,opt,name=album_name,json=albumName,proto3" json:"album_name,omitempty"`
	// Play duration in seconds
	Duration int32 `protobuf:"varint,7,opt,name=duration,proto3" json:"duration,omitempty"`
	// Play timestamp
	PlayedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=played_at,json=playedAt,proto3" json:"played_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayHistory) Reset() {
	*x = PlayHistory{}
	mi := &file_user_v1_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayHistory) ProtoMessage() {}

func (x *PlayHistory) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayHistory.ProtoReflect.Descriptor instead.
func (*PlayHistory) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{26}
}

func (x *PlayHistory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlayHistory) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlayHistory) GetSongId() string {
	if x != nil {
		return x.SongId
	}
	return ""
}

func (x *PlayHistory) GetSongName() string {
	if x != nil {
		return x.SongName
	}
	return ""
}

func (x *PlayHistory) GetArtistName() string {
	if x != nil {
		return x.ArtistName
	}
	return ""
}

func (x *PlayHistory) GetAlbumName() string {
	if x != nil {
		return x.AlbumName
	}
	return ""
}

func (x *PlayHistory) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *PlayHistory) GetPlayedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PlayedAt
	}
	return nil
}

// Playlist represents a user-created playlist.
type Playlist struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique playlist ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// User ID
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Playlist name
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Cover image URL
	CoverUrl string `protobuf:"bytes,4,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	// Whether the playlist is public
	IsPublic bool `protobuf:"varint,5,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	// Song count (redundant for fast display)
	SongCount int32 `protobuf:"varint,6,opt,name=song_count,json=songCount,proto3" json:"song_count,omitempty"`
	// Creation timestamp
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Playlist) Reset() {
	*x = Playlist{}
	mi := &file_user_v1_user_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Playlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Playlist) ProtoMessage() {}

func (x *Playlist) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Playlist.ProtoReflect.Descriptor instead.
func (*Playlist) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{27}
}

func (x *Playlist) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Playlist) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Playlist) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Playlist) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *Playlist) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *Playlist) GetSongCount() int32 {
	if x != nil {
		return x.SongCount
	}
	return 0
}

func (x *Playlist) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Playlist) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// PlaylistSong represents a song in a playlist.
type PlaylistSong struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Playlist ID
	PlaylistId string `protobuf:"bytes,1,opt,name=playlist_id,json=playlistId,proto3" json:"playlist_id,omitempty"`
	// Song ID
	SongId string `protobuf:"bytes,2,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
	// Position in playlist (1-based)
	Position int32 `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	// When the song was added
	AddedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaylistSong) Reset() {
	*x = PlaylistSong{}
	mi := &file_user_v1_user_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaylistSong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaylistSong) ProtoMessage() {}

func (x *PlaylistSong) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaylistSong.ProtoReflect.Descriptor instead.
func (*PlaylistSong) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{28}
}

func (x *PlaylistSong) GetPlaylistId() string {
	if x != nil {
		return x.PlaylistId
	}
	return ""
}

func (x *PlaylistSong) GetSongId() string {
	if x != nil {
		return x.SongId
	}
	return ""
}

func (x *PlaylistSong) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *PlaylistSong) GetAddedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AddedAt
	}
	return nil
}

var File_user_v1_user_proto protoreflect.FileDescriptor

const file_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x12user/v1/user.proto\x12\auser.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xac\x01\n" +
	"\x12AddFavoriteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.user.v1.FavoriteTypeR\x04type\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x125\n" +
	"\bmetadata\x18\x04 \x01(\v2\x19.user.v1.FavoriteMetadataR\bmetadata\"q\n" +
	"\x13AddFavoriteResponse\x12\x1f\n" +
	"\vfavorite_id\x18\x01 \x01(\tR\n" +
	"favoriteId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"Q\n" +
	"\x15RemoveFavoriteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vfavorite_id\x18\x02 \x01(\tR\n" +
	"favoriteId\"2\n" +
	"\x16RemoveFavoriteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8b\x01\n" +
	"\x14ListFavoritesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.user.v1.FavoriteTypeR\x04type\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x8f\x01\n" +
	"\x15ListFavoritesResponse\x12/\n" +
	"\tfavorites\x18\x01 \x03(\v2\x11.user.v1.FavoriteR\tfavorites\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xc2\x01\n" +
	"\x15AddPlayHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\asong_id\x18\x02 \x01(\tR\x06songId\x12\x1b\n" +
	"\tsong_name\x18\x03 \x01(\tR\bsongName\x12\x1f\n" +
	"\vartist_name\x18\x04 \x01(\tR\n" +
	"artistName\x12\x1d\n" +
	"\n" +
	"album_name\x18\x05 \x01(\tR\talbumName\x12\x1a\n" +
	"\bduration\x18\x06 \x01(\x05R\bduration\"\xa0\x01\n" +
	"\x16AddPlayHistoryResponse\x12\x1d\n" +
	"\n" +
	"history_id\x18\x01 \x01(\tR\thistoryId\x127\n" +
	"\tplayed_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bplayedAt\x12.\n" +
	"\x13evicted_old_history\x18\x03 \x01(\bR\x11evictedOldHistory\"b\n" +
	"\x16ListPlayHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x90\x01\n" +
	"\x17ListPlayHistoryResponse\x12.\n" +
	"\ahistory\x18\x01 \x03(\v2\x14.user.v1.PlayHistoryR\ahistory\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"~\n" +
	"\x15CreatePlaylistRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tcover_url\x18\x03 \x01(\tR\bcoverUrl\x12\x1b\n" +
	"\tis_public\x18\x04 \x01(\bR\bisPublic\"G\n" +
	"\x16CreatePlaylistResponse\x12-\n" +
	"\bplaylist\x18\x01 \x01(\v2\x11.user.v1.PlaylistR\bplaylist\"\xb2\x01\n" +
	"\x15UpdatePlaylistRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vplaylist_id\x18\x02 \x01(\tR\n" +
	"playlistId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tcover_url\x18\x04 \x01(\tR\bcoverUrl\x12 \n" +
	"\tis_public\x18\x05 \x01(\bH\x00R\bisPublic\x88\x01\x01B\f\n" +
	"\n" +
	"_is_public\"G\n" +
	"\x16UpdatePlaylistResponse\x12-\n" +
	"\bplaylist\x18\x01 \x01(\v2\x11.user.v1.PlaylistR\bplaylist\"Q\n" +
	"\x15DeletePlaylistRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vplaylist_id\x18\x02 \x01(\tR\n" +
	"playlistId\"2\n" +
	"\x16DeletePlaylistResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"/\n" +
	"\x14ListPlaylistsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"H\n" +
	"\x15ListPlaylistsResponse\x12/\n" +
	"\tplaylists\x18\x01 \x03(\v2\x11.user.v1.PlaylistR\tplaylists\"\x89\x01\n" +
	"\x18AddSongToPlaylistRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vplaylist_id\x18\x02 \x01(\tR\n" +
	"playlistId\x12\x17\n" +
	"\asong_id\x18\x03 \x01(\tR\x06songId\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x05R\bposition\"T\n" +
	"\x19AddSongToPlaylistResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"song_count\x18\x02 \x01(\x05R\tsongCount\"r\n" +
	"\x1dRemoveSongFromPlaylistRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vplaylist_id\x18\x02 \x01(\tR\n" +
	"playlistId\x12\x17\n" +
	"\asong_id\x18\x03 \x01(\tR\x06songId\"Y\n" +
	"\x1eRemoveSongFromPlaylistResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"song_count\x18\x02 \x01(\x05R\tsongCount\":\n" +
	"\x17GetPlaylistSongsRequest\x12\x1f\n" +
	"\vplaylist_id\x18\x01 \x01(\tR\n" +
	"playlistId\"G\n" +
	"\x18GetPlaylistSongsResponse\x12+\n" +
	"\x05songs\x18\x01 \x03(\v2\x15.user.v1.PlaylistSongR\x05songs\"\xed\x01\n" +
	"\bFavorite\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12)\n" +
	"\x04type\x18\x03 \x01(\x0e2\x15.user.v1.FavoriteTypeR\x04type\x12\x1b\n" +
	"\ttarget_id\x18\x04 \x01(\tR\btargetId\x125\n" +
	"\bmetadata\x18\x05 \x01(\v2\x19.user.v1.FavoriteMetadataR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"[\n" +
	"\x10FavoriteMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06artist\x18\x02 \x01(\tR\x06artist\x12\x1b\n" +
	"\tcover_url\x18\x03 \x01(\tR\bcoverUrl\"\x81\x02\n" +
	"\vPlayHistory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\asong_id\x18\x03 \x01(\tR\x06songId\x12\x1b\n" +
	"\tsong_name\x18\x04 \x01(\tR\bsongName\x12\x1f\n" +
	"\vartist_name\x18\x05 \x01(\tR\n" +
	"artistName\x12\x1d\n" +
	"\n" +
	"album_name\x18\x06 \x01(\tR\talbumName\x12\x1a\n" +
	"\bduration\x18\a \x01(\x05R\bduration\x127\n" +
	"\tplayed_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bplayedAt\"\x96\x02\n" +
	"\bPlaylist\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tcover_url\x18\x04 \x01(\tR\bcoverUrl\x12\x1b\n" +
	"\tis_public\x18\x05 \x01(\bR\bisPublic\x12\x1d\n" +
	"\n" +
	"song_count\x18\x06 \x01(\x05R\tsongCount\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9b\x01\n" +
	"\fPlaylistSong\x12\x1f\n" +
	"\vplaylist_id\x18\x01 \x01(\tR\n" +
	"playlistId\x12\x17\n" +
	"\asong_id\x18\x02 \x01(\tR\x06songId\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\x05R\bposition\x125\n" +
	"\badded_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aaddedAt*\x8e\x01\n" +
	"\fFavoriteType\x12\x1d\n" +
	"\x19FAVORITE_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12FAVORITE_TYPE_SONG\x10\x01\x12\x17\n" +
	"\x13FAVORITE_TYPE_ALBUM\x10\x02\x12\x18\n" +
	"\x14FAVORITE_TYPE_ARTIST\x10\x03\x12\x14\n" +
	"\x10FAVORITE_TYPE_MV\x10\x042\x8c\b\n" +
	"\vUserService\x12H\n" +
	"\vAddFavorite\x12\x1b.user.v1.AddFavoriteRequest\x1a\x1c.user.v1.AddFavoriteResponse\x12Q\n" +
	"\x0eRemoveFavorite\x12\x1e.user.v1.RemoveFavoriteRequest\x1a\x1f.user.v1.RemoveFavoriteResponse\x12N\n" +
	"\rListFavorites\x12\x1d.user.v1.ListFavoritesRequest\x1a\x1e.user.v1.ListFavoritesResponse\x12Q\n" +
	"\x0eAddPlayHistory\x12\x1e.user.v1.AddPlayHistoryRequest\x1a\x1f.user.v1.AddPlayHistoryResponse\x12T\n" +
	"\x0fListPlayHistory\x12\x1f.user.v1.ListPlayHistoryRequest\x1a .user.v1.ListPlayHistoryResponse\x12Q\n" +
	"\x0eCreatePlaylist\x12\x1e.user.v1.CreatePlaylistRequest\x1a\x1f.user.v1.CreatePlaylistResponse\x12Q\n" +
	"\x0eUpdatePlaylist\x12\x1e.user.v1.UpdatePlaylistRequest\x1a\x1f.user.v1.UpdatePlaylistResponse\x12Q\n" +
	"\x0eDeletePlaylist\x12\x1e.user.v1.DeletePlaylistRequest\x1a\x1f.user.v1.DeletePlaylistResponse\x12N\n" +
	"\rListPlaylists\x12\x1d.user.v1.ListPlaylistsRequest\x1a\x1e.user.v1.ListPlaylistsResponse\x12Z\n" +
	"\x11AddSongToPlaylist\x12!.user.v1.AddSongToPlaylistRequest\x1a\".user.v1.AddSongToPlaylistResponse\x12i\n" +
	"\x16RemoveSongFromPlaylist\x12&.user.v1.RemoveSongFromPlaylistRequest\x1a'.user.v1.RemoveSongFromPlaylistResponse\x12W\n" +
	"\x10GetPlaylistSongs\x12 .user.v1.GetPlaylistSongsRequest\x1a!.user.v1.GetPlaylistSongsResponseB=Z;github.com/listen-stream/server/shared/proto/user/v1;userv1b\x06proto3"

var (
	file_user_v1_user_proto_rawDescOnce sync.Once
	file_user_v1_user_proto_rawDescData []byte
)

func file_user_v1_user_proto_rawDescGZIP() []byte {
	file_user_v1_user_proto_rawDescOnce.Do(func() {
		file_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)))
	})
	return file_user_v1_user_proto_rawDescData
}

var file_user_v1_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_user_v1_user_proto_goTypes = []any{
	(FavoriteType)(0),                      // 0: user.v1.FavoriteType
	(*AddFavoriteRequest)(nil),             // 1: user.v1.AddFavoriteRequest
	(*AddFavoriteResponse)(nil),            // 2: user.v1.AddFavoriteResponse
	(*RemoveFavoriteRequest)(nil),          // 3: user.v1.RemoveFavoriteRequest
	(*RemoveFavoriteResponse)(nil),         // 4: user.v1.RemoveFavoriteResponse
	(*ListFavoritesRequest)(nil),           // 5: user.v1.ListFavoritesRequest
	(*ListFavoritesResponse)(nil),          // 6: user.v1.ListFavoritesResponse
	(*AddPlayHistoryRequest)(nil),          // 7: user.v1.AddPlayHistoryRequest
	(*AddPlayHistoryResponse)(nil),         // 8: user.v1.AddPlayHistoryResponse
	(*ListPlayHistoryRequest)(nil),         // 9: user.v1.ListPlayHistoryRequest
	(*ListPlayHistoryResponse)(nil),        // 10: user.v1.ListPlayHistoryResponse
	(*CreatePlaylistRequest)(nil),          // 11: user.v1.CreatePlaylistRequest
	(*CreatePlaylistResponse)(nil),         // 12: user.v1.CreatePlaylistResponse
	(*UpdatePlaylistRequest)(nil),          // 13: user.v1.UpdatePlaylistRequest
	(*UpdatePlaylistResponse)(nil),         // 14: user.v1.UpdatePlaylistResponse
	(*DeletePlaylistRequest)(nil),          // 15: user.v1.DeletePlaylistRequest
	(*DeletePlaylistResponse)(nil),         // 16: user.v1.DeletePlaylistResponse
	(*ListPlaylistsRequest)(nil),           // 17: user.v1.ListPlaylistsRequest
	(*ListPlaylistsResponse)(nil),          // 18: user.v1.ListPlaylistsResponse
	(*AddSongToPlaylistRequest)(nil),       // 19: user.v1.AddSongToPlaylistRequest
	(*AddSongToPlaylistResponse)(nil),      // 20: user.v1.AddSongToPlaylistResponse
	(*RemoveSongFromPlaylistRequest)(nil),  // 21: user.v1.RemoveSongFromPlaylistRequest
	(*RemoveSongFromPlaylistResponse)(nil), // 22: user.v1.RemoveSongFromPlaylistResponse
	(*GetPlaylistSongsRequest)(nil),        // 23: user.v1.GetPlaylistSongsRequest
	(*GetPlaylistSongsResponse)(nil),       // 24: user.v1.GetPlaylistSongsResponse
	(*Favorite)(nil),                       // 25: user.v1.Favorite
	(*FavoriteMetadata)(nil),               // 26: user.v1.FavoriteMetadata
	(*PlayHistory)(nil),                    // 27: user.v1.PlayHistory
	(*Playlist)(nil),                       // 28: user.v1.Playlist
	(*PlaylistSong)(nil),                   // 29: user.v1.PlaylistSong
	(*timestamppb.Timestamp)(nil),          // 30: google.protobuf.Timestamp
}
var file_user_v1_user_proto_depIdxs = []int32{
	0,  // 0: user.v1.AddFavoriteRequest.type:type_name -> user.v1.FavoriteType
	26, // 1: user.v1.AddFavoriteRequest.metadata:type_name -> user.v1.FavoriteMetadata
	30, // 2: user.v1.AddFavoriteResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 3: user.v1.ListFavoritesRequest.type:type_name -> user.v1.FavoriteType
	25, // 4: user.v1.ListFavoritesResponse.favorites:type_name -> user.v1.Favorite
	30, // 5: user.v1.AddPlayHistoryResponse.played_at:type_name -> google.protobuf.Timestamp
	27, // 6: user.v1.ListPlayHistoryResponse.history:type_name -> user.v1.PlayHistory
	28, // 7: user.v1.CreatePlaylistResponse.playlist:type_name -> user.v1.Playlist
	28, // 8: user.v1.UpdatePlaylistResponse.playlist:type_name -> user.v1.Playlist
	28, // 9: user.v1.ListPlaylistsResponse.playlists:type_name -> user.v1.Playlist
	29, // 10: user.v1.GetPlaylistSongsResponse.songs:type_name -> user.v1.PlaylistSong
	0,  // 11: user.v1.Favorite.type:type_name -> user.v1.FavoriteType
	26, // 12: user.v1.Favorite.metadata:type_name -> user.v1.FavoriteMetadata
	30, // 13: user.v1.Favorite.created_at:type_name -> google.protobuf.Timestamp
	30, // 14: user.v1.PlayHistory.played_at:type_name -> google.protobuf.Timestamp
	30, // 15: user.v1.Playlist.created_at:type_name -> google.protobuf.Timestamp
	30, // 16: user.v1.Playlist.updated_at:type_name -> google.protobuf.Timestamp
	30, // 17: user.v1.PlaylistSong.added_at:type_name -> google.protobuf.Timestamp
	1,  // 18: user.v1.UserService.AddFavorite:input_type -> user.v1.AddFavoriteRequest
	3,  // 19: user.v1.UserService.RemoveFavorite:input_type -> user.v1.RemoveFavoriteRequest
	5,  // 20: user.v1.UserService.ListFavorites:input_type -> user.v1.ListFavoritesRequest
	7,  // 21: user.v1.UserService.AddPlayHistory:input_type -> user.v1.AddPlayHistoryRequest
	9,  // 22: user.v1.UserService.ListPlayHistory:input_type -> user.v1.ListPlayHistoryRequest
	11, // 23: user.v1.UserService.CreatePlaylist:input_type -> user.v1.CreatePlaylistRequest
	13, // 24: user.v1.UserService.UpdatePlaylist:input_type -> user.v1.UpdatePlaylistRequest
	15, // 25: user.v1.UserService.DeletePlaylist:input_type -> user.v1.DeletePlaylistRequest
	17, // 26: user.v1.UserService.ListPlaylists:input_type -> user.v1.ListPlaylistsRequest
	19, // 27: user.v1.UserService.AddSongToPlaylist:input_type -> user.v1.AddSongToPlaylistRequest
	21, // 28: user.v1.UserService.RemoveSongFromPlaylist:input_type -> user.v1.RemoveSongFromPlaylistRequest
	23, // 29: user.v1.UserService.GetPlaylistSongs:input_type -> user.v1.GetPlaylistSongsRequest
	2,  // 30: user.v1.UserService.AddFavorite:output_type -> user.v1.AddFavoriteResponse
	4,  // 31: user.v1.UserService.RemoveFavorite:output_type -> user.v1.RemoveFavoriteResponse
	6,  // 32: user.v1.UserService.ListFavorites:output_type -> user.v1.ListFavoritesResponse
	8,  // 33: user.v1.UserService.AddPlayHistory:output_type -> user.v1.AddPlayHistoryResponse
	10, // 34: user.v1.UserService.ListPlayHistory:output_type -> user.v1.ListPlayHistoryResponse
	12, // 35: user.v1.UserService.CreatePlaylist:output_type -> user.v1.CreatePlaylistResponse
	14, // 36: user.v1.UserService.UpdatePlaylist:output_type -> user.v1.UpdatePlaylistResponse
	16, // 37: user.v1.UserService.DeletePlaylist:output_type -> user.v1.DeletePlaylistResponse
	18, // 38: user.v1.UserService.ListPlaylists:output_type -> user.v1.ListPlaylistsResponse
	20, // 39: user.v1.UserService.AddSongToPlaylist:output_type -> user.v1.AddSongToPlaylistResponse
	22, // 40: user.v1.UserService.RemoveSongFromPlaylist:output_type -> user.v1.RemoveSongFromPlaylistResponse
	24, // 41: user.v1.UserService.GetPlaylistSongs:output_type -> user.v1.GetPlaylistSongsResponse
	30, // [30:42] is the sub-list for method output_type
	18, // [18:30] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_user_v1_user_proto_init() }
func file_user_v1_user_proto_init() {
	if File_user_v1_user_proto != nil {
		return
	}
	file_user_v1_user_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_user_proto_goTypes,
		DependencyIndexes: file_user_v1_user_proto_depIdxs,
		EnumInfos:         file_user_v1_user_proto_enumTypes,
		MessageInfos:      file_user_v1_user_proto_msgTypes,
	}.Build()
	File_user_v1_user_proto = out.File
	file_user_v1_user_proto_goTypes = nil
	file_user_v1_user_proto_depIdxs = nil
}
